### PR TITLE
Return the state fragment to the caller if the action is a reducer.

### LINKED ISSUE #242: Access current state in onremove?
For the transitions solution I've got to work in hyperapp-apps, there needs to be a way to access the state of the app when onremove lifecycle methods are *called*.  Not the state that was when they were bound.

The onremove handler can call actions. Actions will have access to the state as it is at the time they are called. But you can't get anything out of them.

There are three solutions I can see:

A) Either the signature for on remove handlers is augmented to look like: `... onremove={(el, doRemove, state) => {...}}`

or B) We can add the concept of getters alongside actions. Getters would work just like actions, except that what they return goes back out to the caller, instead of modifying the state

or C) Along the lines of what @dodekeract has suggested before: We change the behavior of actions to return whatever they return without modifying the state, and give them access to a "setState" or whatever function they can use to perform state mutations.

From what I understand, the API is pretty much locked down so I don't have much hope for B or C. A could happen but it's the least elegant / general. It's very specific to my problem.

### PR DESCRIPTION
**Pull request by jbucaran**
Now actions.myAction will return whatever the original myAction function returns. Before, this was only true if myAction returned a Promise.

## Example

```jsx
app({
...
  actions: {
    getState: state => state
  }
...
})
```

Diff: 0 bytes.

Fix #242.

### CODE REVIEW

**Comment by jbucaran** [comment]
:tada: 💯

**Comment by dodekeract** [comment]
So does this still update the state or did you just implement my suggestion regarding getting rid of the weird return to update functionality?

**Comment by jbucaran** [comment]
@dodekeract This returns the result of an action to the caller, whatever that may be. 

This just helps with @zaceno's use case without breaking the API. 

Maybe @zaceno can explain it better?

**Comment by zaceno** [comment]
@dodekeract: still updates state. I kind of still wish we could have getters, i.e. same as actions but *dont* update state -- just return out whatever the inner function returns from the state. 

... thinking maybe you'd be more ok with the behavior of actions if there were getters to use for when you *don't* want the state to update?

**Comment by jbucaran** [comment]
@zaceno Those are the old effects no? Maybe we can come up with another clever way?

**Comment by zaceno** [comment]
@jbucaran -- that's right! Hadn't thought of it before because I always thought of effects as a way of batching and/or deferring reducers -- not as a way of getting/processing data from the state -- but the old effects could work for that too.

I'm open to thinking about & discussing clever ways to get that behavior back. But to be fair you shouldn't give my opinons on hyperapp's state management too much weight, since I've switched my personal projects from away from hyperapp, to picodom + my home made state management solution (which I'm still very much experimenting with)

Anyhow, here are my thoughts: 

I feel like we've already  "violated" the reducer principle when we allowed actions to return a promise, and in that case *not* update the state. So we could always take that a step further, with other "magical" ways of returning in actions, that don't cause state updates.  Like perhaps if what you returned was an object `{update: false, result: x} then the action would return x without updating state.

I grant you, that's not very pretty. I'd much prefer something along the lines of what @dodekeract already suggested, which is that actions always return with the inner-returned value, and *don't* update state by default. Instead they are passed a `setState` or similar function to be used inside the action, when you actually want to set the state.

**Comment by jbucaran** [comment]
@zaceno Thanks for the feedback! Definitely, something to think about.

**Comment by dodekeract** [comment]
> without breaking the API — @jbucaran

Not true. In complex actions I'm often using `return actions.someOtherAction()` to end the action execution and forward it to a different action.

Now, this would update the state twice which may even lead to race conditions or hard to track down bugs.

**Comment by jbucaran** [comment]
@dodekeract I see what you are saying. I can try to give priority to #90 (leaving #238 for later) and see if that helps, otherwise, we can reverse this.

**Pull request merged**
