### PR TITLE
fixed IE 10 Error: Invalid Argument on insertBefore

### PR DESCRIPTION
**Pull request by sam-chuang**
Fixed IE 10 Error: Invalid Argument on insertBefore

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
Temporarily "on hold" as per #446 until a decision is made.

**Comment by sam-chuang** [comment]
Got it, thank~~

Let me know if you need any further change for this PR

**Comment by JorgeBucaran** [comment]
@sam-chuang Sure! In the meantime, please report back any further issues you have with IE if you have any. 👋

**Comment by JorgeBucaran** [comment]
@sam-chuang I had to push --force to master and rewriting history completely messes up open PRs on GitHub. Sorry for the disaster! 🙇

**Comment by selfup** [comment]
Yea I would recommend cloning your fork into a new dir, merging this branch from origin (in a different branch) - (without updating the history first from this upstream) then you won't have to write the code all over again 🎉 You just might have to learn some more advanced git workflow, but hey it's worth it 🙏

**Pull request closed without merging**
