### PR TITLE
Fix onremove() ordering

### PR DESCRIPTION
**Pull request by infinnie**
Fixing #681.

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Partly? :D

**Comment by infinnie** [comment]
Partly for it being untested.

**Comment by jorgebucaran** [comment]
Gotcha. This is nice try attempt. Ultimately, storing the element in the virtual node will solve the problem, help simplify diffing and improve performance, so while this is fun and you are free to keep doing your best, this is not the route I'll choose.

**Comment by infinnie** [comment]
As of commit https://github.com/infinnie/hyperapp/commit/b12f9bd5ccdb00540b8d2630a8cba256f3571377 tests could be passed now. But I still don’t know why it even works.

**Comment by jorgebucaran** [comment]
@infinnie Because there's no test documenting the said onremove bug.

**Comment by infinnie** [comment]
@jorgebucaran I mean the original tests.
Also maybe @mindplay-dk should be held responsible for documenting the `onremove()` test.

**Comment by infinnie** [comment]
@jorgebucaran ok I’ve added a preliminary test for that purpose.

**Comment by infinnie** [comment]
Seems that much of the problem of reordering should have been fixed as of #663, but that brought forth a problem as I stated in https://github.com/hyperapp/hyperapp/issues/681#issuecomment-384141348:
>> Just by the way: what would we expect to happen if two asynchronous element removals happen consecutively, so that when one element is being removed we start to remove the second one?
And this PR then solves that new problem.

**Comment by infinnie** [comment]
@jorgebucaran #685

**Comment by mindplay-dk** [comment]
@infinnie did you try this on the [nightmare fiddle](https://jsfiddle.net/mindplay/omovhf25/) I came up with to ruin Jorge's day? 😀

**Comment by infinnie** [comment]
@mindplay-dk An error occurred that
> Assignment to read-only properties is not allowed in strict mode.

**Comment by infinnie** [comment]
@mindplay-dk An error occurred that
> 'ultradom' is not defined

**Comment by infinnie** [comment]
@mindplay-dk See also https://jsfiddle.net/y7a2jc55/ that shows where the original Ultradom is wrong.

**Comment by mindplay-dk** [comment]
@infinnie I wrote this test a while back to document the reordering issue with deferred removals:

https://github.com/mindplay-dk/picodom/commit/2b0784b05c4d12f9cdf2471b2eccae327c92aa51

I'm not sure if this covers the more complex issue demonstrated by the nightmare fiddle - it was a long time ago and my attentions are elsewhere at the moment.

I wrote a [more aggressive test](https://bitbucket.org/mindplaydk/domsync/src/7150a9028fd1ba0cbb6279126f0ea0aa21e7ec89/src/test.tsx?at=master&fileviewer=file-view-default#test.tsx-187) (for my own dead project) for reordering, but that doesn't cover the issue with deferred removals.

Probably what's needed is a more minimal/controlled test of some sort, along the lines of [this](https://jsfiddle.net/mindplay/gcd663fx/) fiddle, which you could probably turn into a test by hoisting the removal callbacks, same as I did in my first test.

**Pull request closed without merging**
