### PR TITLE
Add test for when plain-string vnodes are removed

### PR DESCRIPTION
**Pull request by zaceno**
This test breaks the suite because there is currently a bug in hyperapp, that occurs when textnodes are removed, where we check for `node.data.onRemove` without knowing for sure that `node.data` exists (which it doesn't, if node is just a plain string). Causes a TypeError to be thrown.

### CODE REVIEW

**Comment by zaceno** [comment]
Submitted as verification of:

https://github.com/hyperapp/hyperapp/pull/193

... and to prevent regressions in the future :)

**Comment by maraisr** [comment]
@zaceno might just have to merge master back into your branch, and I believe the tests should pass again.

**Comment by maraisr** [comment]
Looking like this guy can be merged? @jbucaran @zaceno?

**Comment by jbucaran** [comment]
Whoops, forgot about this. Thanks @zaceno and @maraisr.

**Comment by maraisr** [comment]
haha @jbucaran all good man! 

Are we going to see a patch version bump?

**Comment by lukejacksonn** [comment]
+1 on the patch version bump. Would be great if we could.. I'm waiting on [this](https://github.com/hyperapp/hyperapp/commit/451b0c22699305d91d8159c668c2619da17df25d) to fix svgs which could fall under a patch (although maybe its minor 😕)

**Comment by dodekeract** [comment]
I see no reason why we should ever delay a non-breaking bugfix.

**Pull request merged**
