### PR TITLE
Bit of a refactoring of the docs to make it better findable.

### PR DESCRIPTION
**Pull request by Alber70g**
See also issue #514

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
@Alber70g Why?

**Comment by Alber70g** [comment]
As I find it struggling to not have separate docs for each of the concepts/functions in Hyperapp (and [others](https://www.reddit.com/r/programming/comments/7mphvg/introducing_hyperapp_10_1_kb_javascript_library/drwf6jf/) as well), I thought it'd be good to create them.

**Comment by JorgeBucaran** [comment]
> I'm still struggling with how to format the documents so they're not too overwhelming, but still describe what can be done with each part.

I know. This is really hard, that's why I published 1.0 with the current docs. 🤔

**Comment by JorgeBucaran** [comment]
Does this PR depend on your other PR?

**Pull request closed without merging**
