### PR TITLE
Added Flow type annotations

### PR DESCRIPTION
**Pull request by nitin42**
Initially I've added types to `h.js`. I wanted to know about the schema for app which include state, view, events, actions, namespace. Review this and then we can discuss further about adding types to `App.js`

### CODE REVIEW

**Comment by Swizz** [comment]
Personally I vote in favor of Typescript

**Comment by jbucaran** [comment]
We are going through a similar situation in picodom. Both @ngryman and @pspeter3 made compelling arguments against it and in favor respectively. It's a tough one.

- https://github.com/picodom/picodom/issues/10
- https://github.com/picodom/picodom/issues/7

**Comment by Swizz** [comment]
I tried both, and both are similar but different.

The main purpose is what do you want types for?
* Expose a typed API
* Internal typing for ensure code
* Both

I think Flow is better for the second one, because it is able to catch typing trouble without explicit type. Typescript is just a transpiler without explicit typing.

For the first one, Typescript is better as long as your targeted devs use Typescript otherwise, Flow is better.

I prefer Typescript in everyday use, because Typecript is already an ES6 transpiler where Flow is not.

Both are similar but different; And this is a non-ending debate.
* Typescript is a compiler/transpiler with typing capabilities.
* Flow is only a type checker.

So you will need to ask your contributors or take a personal choice.

**Comment by jbucaran** [comment]
@nitin42 Would you like to tackle #87 too?

**Comment by nitin42** [comment]
Umm.. refer to this article http://thejameskyle.com/adopting-flow-and-typescript.html and I am sure you will come to know about both of them. There was a same discussion earlier with me and an another maintainer of a different library about adopting type system and we decided to use Flow rather than Typescript. The article is not biased but Flow will be much better option.

**Comment by nitin42** [comment]
I will start working on creating the Flow declaration files if we choose Flow. Let me know!

**Comment by SkaterDad** [comment]
For what it's worth, Typescript 2.3+ can type-check javascript files (no transpiling required).   In this way, it can be used similarly to flow, but only using JS-doc style comments.  This seems to be the least intrusive way to introduce type checking in my opinion (minifier already strips comments, so no intermediate JS file has to be created), so maybe it's an option?
https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files

**Comment by Swizz** [comment]
Another reading : https://github.com/niieani/typescript-vs-flowtype

Another concern could be, can I take benefits of Type with Typescript if Hyperapp use Flow type ? 
Or do I need to write a `.d.ts` too ?

So, could you use Flow for internal type checking usage and provide a `.d.ts` file for the public API ?

**Comment by jbucaran** [comment]
I think we should first do #87. 🤔

**Comment by Swizz** [comment]
@jbucaran `.d.ts` is more than editor stuffs, lot of Typescript developer are one the ways to use the strict mode of typescript, that require library to have a declaration file.
Some of them, are regrouped in a unofficial (I mean not maintained by libraries authors) repo : [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

I  repeat myself, but I think we need to know what is the main purpose of typing : To expose a typed API or for Internal typing to ensure code.

**Comment by jbucaran** [comment]
> I repeat myself, but I think we need to know what is the main purpose of typing: To expose a typed API or for Internal typing to ensure code.

What would be a good compromise in your opinion?

**Comment by Swizz** [comment]
If you are targeting developers experience : A declaration file will be sufficiant (Typescript, Flow, Both ?)
This will allow you to provide a typed API and communicated about function/api and types in a normalised way.

If your wish is to ensure code quality and testing, you can move into the way to add type into your code (Flow for just type checking, Typescript for both type checking and transpiling).

**Comment by jbucaran** [comment]
@Swizz Parts of the code are optimized by hand, so I'd like to avoid transpilation. 

Flow, on the other hand may be worth adding to the project. 🤔

**Comment by Swizz** [comment]
Only declaration file could be a great consensus. You will be able to type only the things that are publicly exposed without doing anything to your code base.

An example of `.d.ts` file for a `NotReact.createElement` implementation : https://github.com/Swizz/snabbdom-pragma/blob/develop/snabbdom-pragma.d.ts

**Comment by whaaaley** [comment]
I vote for no change 😬 . I think the code base is small enough extra tooling would be... extra. If type checking must happen, I'd rather not convert everything to a new language.

**Comment by jbucaran** [comment]
@nitin42 How do you feel about this? Would you like to help with #87 instead?

Thanks for igniting this discussion!

**Comment by Swizz** [comment]
So declaration file without touching the actual code, this is just another file in the root directory 🎉 👍 

We only need declarations for exported functions and an interface for the `app()` parameter.

**Comment by nitin42** [comment]
@jbucaran #87 refers to adding Typescript definition file. Right ? I am comfortable with both (I know Typescript and Flow). Will start working on this as soon as I make the notes about the codebase! Good ?

**Comment by nitin42** [comment]
@whaaaley I think you're also right. API will change and size of the codebase is also small. We could work on type definitions instead and add types to the actual codebase later! Sounds good ?

**Comment by jbucaran** [comment]
@nitin42 Sounds good!

**Comment by pspeter3** [comment]
I think this is a great step! Many projects do not write tests that the type definitions are actually valid so perhaps adding a test for that would be useful?

**Comment by nitin42** [comment]
Could you elaborate it further ?

**Comment by selfup** [comment]
I would rather stick with Flow on this kind of project. Mostly for dev experience :+1:

**Comment by pspeter3** [comment]
Basically, the DTS is similar to a caching issue. My thought is that we can write a simple TypeScript file that tests that the code compiles correctly and then check in the test runtime that the types are correct.

**Comment by nitin42** [comment]
I am not sure but I think it would be unnecessary to do so. Write declaration files and test further ? Instead we could use a static checker and check the types (like Flow does).

**Comment by pspeter3** [comment]
Are you proposing that Flow will check the validity of the DTS? If so, great.

**Comment by nitin42** [comment]
Yes! Flow does this implicitly. 

The technique is that, `flow-typed` repo relies on `suppress_comment` configuration option in `.flowconfig`

```
[options]
suppress_comment=\\(.\\|\n\\)*\\$ExpectError
```

Now we can use this comment anywhere in declaration file for the module. If the line that follows the comment raises a flow error, it will be suppressed else flow will raise the error. Simple ?

**Comment by nitin42** [comment]
@selfup is right ! Typescript could increase the complexity in the project (still not biased 😅 ).

**Comment by pspeter3** [comment]
To be honest, I feel like the momentum for both hyperapp and picodom is against TypeScript and I'm surprised that the support for Flow is so high. That being said, I think both projects are great and have their use cases even if they don't have TypeScript. Therefore, maybe the best course of action is just accept neither will have TypeScript and move on.

**Comment by nitin42** [comment]
It would be much better if both the typings are provided (seen in other libraries also). Then we can upload both the files on their respective repos (flow-typed and DefinitelyTyped). Ok ?

**Comment by nitin42** [comment]
For a complete rewrite, I will stick with Flow!

**Comment by Swizz** [comment]
> It would be much better if both the typings are provided (seen in other libraries also). Then we can upload both the files on their respective repos (flow-typed and DefinitelyTyped). Ok ?

We do not need flow-typed and DefinitelyTyped, we only need to write a `hyperapp.d.ts` file and add it to the package.json.
```json
{
  "main": "dist/hyperapp.js",
  "module": "src/index.js",
  "types": "hyperapp.d.ts",
}
```

I will work on it tomorrow to close this asap

**Comment by Swizz** [comment]
Draft in #87

**Comment by andyrj** [comment]
I didn't think the .d.ts to flow via flowgen was working yet.  Why would only the .d.ts be needed?  Curious if I am not aware of a new solution for that or something.

**Comment by jbucaran** [comment]
> @Swizz In fact, personally I am only asking for a declaration file, not for a complete rewrite into Typescript

I agree.

@nitin42 Do you want to tackle #87 and close here?

**Comment by nitin42** [comment]
👍🏻

**Comment by nitin42** [comment]
Added implementation notes. Needs some work though!

**Comment by jbucaran** [comment]
@nitin42 Thanks! I am still not sure if we'll adopt flow or not, so can you send your implementation notes as a different PR? I'd like to merge that and add it to the docs.

**Comment by nitin42** [comment]
#261 Btwn I think we can close this issue!

**Pull request closed without merging**
