### PR TITLE
Use addEventListener for popstate/hashchange events

### PR DESCRIPTION
**Pull request by itrelease**
With this approach if user will set his own handler on `popstate/hashchange` event it will not reset library behaviour

### CODE REVIEW

**Comment by maraisr** [comment]
Nice pick up @itrelease mate! Consider this merged! :100:

**Comment by jbucaran** [comment]
addEventListener is not available in IE8, which is why I had it like that, but @itrelease brought a good point which I had not considered.

Thanks!

**Comment by maraisr** [comment]
We should look at settling on a "this is what we're going to support", so I don't merge stuff again....

But you're right in that regard.

**Comment by jbucaran** [comment]
@maraisr That's alright, you made the right choice!

**Pull request merged**
