### PR TITLE
Support nodes whose tag is a function.

### PR DESCRIPTION
**Pull request by jbucaran**
HyperApp's architecture is largely based in Flux/Redux and/or the Elm Architecture. There's a single state shared by all the views. Another way to put that, views can't have a local state. 

But what about components? The answer is stateless components.

```jsx
<MyComponent props=...></MyComponent>
```

**Related**
* https://github.com/reactjs/redux/issues/1385
* https://github.com/hyperapp/hyperapp/issues/2
* https://github.com/hyperapp/hyperapp/issues/8

### CODE REVIEW

**Comment by danigb** [comment]
That's a really nice addition 👏👏

**Comment by tunnckoCore** [comment]
Cool!

But i believe it would be better to pass `data` directly and append the `children`, it is how is done in React and etc? I played with this and `mich-h` stuff and kinda don't liked to add `children` "special property" to the props.

```js
	if (typeof tag === "function") {
		tree = tree || []
		data.children = tree
		return tag(data, tree)
	}
```

So

```js
const Foo = (props) => <div id={props.id} className={props.cls}>{props.children}</div>

const Foo2 = (props, children) => <div id={props.id} className={props.cls}>{children}</div>

const foo = <Foo cls="baz qux" id="hi">
  <strong>hello</strong>
</Foo>
```

**Comment by tunnckoCore** [comment]
Hm... No, no, nevermind. Kinda like more your approach when rethink it. It is more clean and explicit.

```jsx
const Foo2 = ({ props, children }) =>
  <div id={props.id} className={props.cls}>{children}</div>
```

**Comment by jbucaran** [comment]
@tunnckoCore Yeah, but who cares? I think some people would. I find this approach cleaner too, but

> It won't be react compatible directly,

But what if it was? That'd be another reason to give HyperApp a chance.

**Comment by tunnckoCore** [comment]
Don't know, I like them either way. Current no-react-compatible is more cleaner.

**Pull request merged**
