### PR TITLE
Update CONTRIBUTING.md: ES3 → ES5

### PR DESCRIPTION
**Pull request by infinnie**
Things like `Array.prototype.map()` are features of ECMAScript 5 (though they could be shimmed to ES 3 too).

Also exports are only available as of ES 6.

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@infinnie You are totally right about <samp>Array.prototype.map</samp>! 🤔

**Comment by jorgebucaran** [comment]
> Also exports are only available as of ES 6.

This was the only exception.

**Comment by jorgebucaran** [comment]
@infinnie What if we rewrite `recycleElement` to not need `.map`? 😏

**Comment by infinnie** [comment]
like rewriting to `jQuery.map()`?

**Comment by jorgebucaran** [comment]
@infinnie Only `recycleElement` would need to be rewritten because it's the only place using `.map`.  This is far from a priority, so I'll go ahead and merge this anyway.

**Comment by jorgebucaran** [comment]
Thanks! @infinnie

**Pull request merged**
