### PR TITLE
JSX tree needs to default the data, and tree to an array.

### PR DESCRIPTION
**Pull request by maraisr**
May as well just default these in the params.

### CODE REVIEW

**Comment by maraisr** [comment]
Hang tight, will have to modify the PR so that we can build out es6 stuff through uglifyjs.

**Comment by jbucaran** [comment]
@maraisr I think that will break in some older versions of node.

**Comment by maraisr** [comment]
Either way think we need to default the `data` to an empty object when it is likely to be sent in as null through babel's jsx transform, same with the `tree` param. It will be sent in as `undefined` hence, we need to test for undefiend and create an empty array rather than creating an array of empty.

**Comment by maraisr** [comment]
On top of that, do you think we should start writing some tests? Ill create a PR for testing, you happy to use Jest?

**Comment by jbucaran** [comment]
@maraisr Tests, yes! I'm not familiar with Jest. I'll have a look. What do you think about https://github.com/substack/tape?

**Comment by maraisr** [comment]
@jbucaran yeah man, that'll be sick.. Tape is nice, IMO jest just has a much nicer cli output I've created a new pr #19 kinda screwed up git in this pr...

**Comment by maraisr** [comment]
@jbucaran #21 is the new PR...

**Comment by jbucaran** [comment]
Tape is a format agnostic, so if we wanted a nice reporter, we'd just pipe tape's output to a reporter :)

**Pull request closed without merging**
