### PR TITLE
Fix route definition format

### PR DESCRIPTION
**Pull request by naugtur**
Not sure if that's all the required updates.

### CODE REVIEW

**Comment by jamen** [comment]
Hey @naugtur.  These are new changes made in  #231 and #233.  If you would like to see [docs for v0.9, you can change to that tag](https://github.com/hyperapp/hyperapp/tree/0.9.2/docs).  However, v1 will be released with what you see there, soon.  Thanks. :tada:

**Comment by jbucaran** [comment]
@naugtur Sorry for the lack of clarity. I'll release a new minor with the new changes a bit later.

**Comment by naugtur** [comment]
Ok. Thx

In that case, examples are outdated.

If you make your plans/roadmap more transparent I might help a bit with getting 1.0 out.

**Comment by jbucaran** [comment]
@naugtur Which examples? I should be able to fix that quickly today.

**Comment by naugtur** [comment]
Sorry I dropped the ball. Router example (the one linked in router docs) doesn't match the docs anymore.

**Pull request closed without merging**
