### PR TITLE
Makes * the fallback route if no matching route is found

### PR DESCRIPTION
**Pull request by lukejacksonn**
As a response to https://github.com/hyperapp/hyperapp/issues/109. Actions taken:

- match function now returns `routes["*"]` when no route is found
- regexify function now returns a regex that will match `.*` when it is given the path `*` 
- Added tests for just `/` route 
- Added `*` route to both tests `view` object

Tests are passing but I would like to discuss if any of the logic could be tidied up!

### CODE REVIEW

**Comment by jbucaran** [comment]
@lukejacksonn Awesome! Let me review this.

Does the router still work for `/`?

**Comment by lukejacksonn** [comment]
yeh because now `/` just gets treated as any other route!

**Comment by lukejacksonn** [comment]
It does demand that the objects passed to `views` has a `*` route though now otherwise it would break.. we could easily add a default view though like a default `404` message

**Comment by jbucaran** [comment]
@lukejacksonn But we could avoid having to specify a `*` property correct?

```jsx
        for (var name in routes) {
            if (name === "*") {
                continue
            }
        ...
      }
```

**Comment by lukejacksonn** [comment]
then what gets returned from `match()`?

**Comment by lukejacksonn** [comment]
If you make line 60 look like this:
`return routes["*"] || function(m,a) { return "404 Not Found" }`

Then the user doesn't need to specify any route at all (this would simply result in "404 Not Found" being rendered)

**Comment by lukejacksonn** [comment]
Adding your snippet has two advantages:

- Means that the order of the routes in the object passed to view doesn't matter (that is the `*` route can be at the top, bottom or somewhere in between), currently it has to be the last route.
- It means that a regex for `*` will not need to be created, so the the logic in `regexify` does not need to be altered. Currently it has been.

This combined with a default 404 message seems like a more robust approach to me.

**Comment by jbucaran** [comment]
@lukejacksonn So, which one should we use?

**Comment by lukejacksonn** [comment]
Both 🎉  I will push it up now

**Comment by lukejacksonn** [comment]
How do you feel about the message `404 Not found`? Something like `No route found for /path` might be more useful for a beginner.

**Comment by jbucaran** [comment]
@lukejacksonn I think we should just throw, no_

**Comment by lukejacksonn** [comment]
ahh yeh, could do

**Comment by jbucaran** [comment]
Thanks a lot @lukejacksonn! I'll take it from here. I'll pull your branch locally, do some mods and ping you again, perhaps you can review it tomorrow? 🙏

**Comment by lukejacksonn** [comment]
Sure! Can't wait 💯

**Comment by tunnckoCore** [comment]
meh.. throwing text..

**Comment by jbucaran** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by lukejacksonn** [comment]
I'm going to close this as it has been merged right?

**Comment by jbucaran** [comment]
@lukejacksonn Not yet, as I am still working on the new plugin architecture. 🙏

**Comment by lukejacksonn** [comment]
Yeh sorry I just wanted rid of those extra commits really! They have been removed now 😅

**Comment by jbucaran** [comment]
The new router is almost ready, but the regex matcher and logic "/" or "*" stuff will not change, so your PR is still quite relevant!

**Pull request merged**
