### PR TITLE
expose updateApp function per hyperapp

### PR DESCRIPTION
**Pull request by selfup**
🎉 #533 #542 

#### Pros

1. Simple
  
#### Cons

1. Memory Leaks (for now until we solve/if we decide to solve)
2. `oncreate` will be fired (each one)
3. `ondestory` needs to be fired (each one)
4. other unknowns

### Please consider using a HOA (Higher Order App)

https://github.com/hyperapp/hyperapp/issues/533#issuecomment-355765388

Brief example of a HOA being used:

```js
const main = injectUpdate(app)(state, actions, view, document.body);

main.updateApp({
  newActions: {
    mult: () => ({ count }) => ({ count: count * 2 }),
  },
  newState: {
    count: 90,
  },
});

// OR

const main = injectUpdate(app)(state, actions, view, document.body);

import('./thing.js')
  .then(({ state: newState, actions: newActions }) => {
    main.updateApp({ newState, newActions });
  });
```

If we decide to delegate to a HOA, we should add a file in the docs `dynamic_loading.md` and explain the reason and point to the issue/PR etc..!

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
@selfup I like:

> other unknowns

😆

**Comment by selfup** [comment]
Heh 😆 You never know!

**Comment by selfup** [comment]
https://github.com/hyperapp/hyperapp/issues/533#issuecomment-355830938

> If we pick the HOA we have two options:
> 
> Extract to userland (under @hyperapp/update)
> Expose from hyperapp const { h, app, updateApp } = hyperapp but that would add a lot of bytes

**Comment by JorgeBucaran** [comment]
I'll experiment with adding core support to calling app multiple times, but as @okwolf commented [here](https://github.com/hyperapp/hyperapp/issues/533#issuecomment-355856008), `updateApp` is a pattern that can be achieved using an HOA. It not even needs to be an "official" package.

**Comment by selfup** [comment]
Yep agreed!

**Pull request closed without merging**
