### PR TITLE
Add VS Code Editor config file to help debug and run Tests from within the Editor

### PR DESCRIPTION
**Pull request by rajaraodv**
VS Code provides excellent support to run and debug tests. i have added two configurations to the .vscode and anyone who opens Hyperapp will get the following:
1.  ***Debug Tests (Current File)*** - This helps us to simply open one of the Test files and put break point to debug.
2. ***Debug All Tests*** -  This is to simply run all the tests.

Following pictures shows how it works and will serve as  documentation:

1. **Debugging Tests (Current File)**

Debugging Current file getting started:
debugging-single-test-file

Debugging file in action:
debugging-single-test-file-in-action

Output of a single test file:
output-single-file

2. **Debug All Tests**
Use this to simply run all tests and ensure everything works. If you see any errors in any file, switch back to the above option and debug that one file.

Output of running all files:
output-all-files

### CODE REVIEW

**Comment by Swizz** [comment]
This is a great resource for learning but I am not really in favor of adding editor specifics things in the Hyperapp main repository.

**Comment by JorgeBucaran** [comment]
This is definitely a super useful resource and I will copy those settings right away, but I am not sure about adding it to the project.

It still would be nice to share this info with the community somehow, via a separate repo for example, or in a wiki, etc.

**Comment by lukejacksonn** [comment]
I would agree with @Swizz and @JorgeBucaran here.. it is a very useful resource but not essential for all hyperapp users.

**Comment by rajaraodv** [comment]
OK, makes sense. Can we have add this to Docs? (under testing section)?

**Comment by lukejacksonn** [comment]
@rajaraodv how about you make a PR showing where you would put it and what it would look like?

**Comment by rajaraodv** [comment]
OK. Closing this.

**Comment by okwolf** [comment]
Someone should publish an npm package for creating/adding launch configs that you could just run with `npx` instead of manually copying this every time you wanted it.

**Comment by selfup** [comment]
oh that would be pretty easy using `fs` 🤔

**Comment by okwolf** [comment]
@selfup wouldn't it just be a Jest launch config? I could use this on non HA projects.

**Comment by selfup** [comment]
Oh right, that makes sense as well 😂

**Pull request closed without merging**
