### PR TITLE
Added a badge for npm download

### PR DESCRIPTION
**Pull request by rishabh09**

### CODE REVIEW

**Comment by Alber70g** [comment]
While you're at it, can you put them on separate lines? Markup doesn't break when they're on separate lines.

**Comment by JorgeBucaran** [comment]
Thanks @rishabh09! I don't know if I want to add more badges, it's already pretty loaded. Please don't close as I'd like to think about it, but I wouldn't hold my breath to it! 😅

**Comment by JorgeBucaran** [comment]
@Alber70g Prettier should do that for you! 😄

**Comment by Alber70g** [comment]
Oh wow that's annoying ;)

**Comment by JorgeBucaran** [comment]
@Alber70g I think I fixed that with `"prettier.proseWrap": false`.

**Comment by JorgeBucaran** [comment]
Sorry folks! I messed up my GPG and had to push --force to master. I didn't know it was going to mess up the PR like this. 🙇🙇  

With regards to adding the downloads badge, I feel there are already too many badges on the README.

**Pull request closed without merging**
