### PR TITLE
Fixed broken link in hello-world.md to vnode.md in issue #545

### PR DESCRIPTION
**Pull request by dance2die**
This is a PR for addressing issue #545 

I've added a `relative path` to the virtual node file.

I've read the contribution page but if this PR doesn't meet the standard, please let me know.

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
Thanks @dance2die! I had some GPG issues and had to push --force to master. I didn't know the PR would be blown up like this. Sorry! 🙇

**Comment by dance2die** [comment]
@JorgeBucaran Don't worry about it. :)
This PR was closed with unmerged commits, by the way.

**Comment by dance2die** [comment]
Followed up to step# on https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c
Let's see if PR can be opened

**Comment by JorgeBucaran** [comment]
@dance2die Nope, I still can't open the PR. 😭

**Pull request closed without merging**
