### PR TITLE
New function to allow `app` creation with inversion of control

### PR DESCRIPTION
**Pull request by etalisoft**
# Inversion of Control

## Why?
The base `app` function that Hyperapp supplies is perfect for covering the common use case.  It can be customized pretty easily with Higher-Order Apps and Higher-Order Components.  Unfortunately HOA/HOC can only take you so far.  Some features need to be implemented inside `app` itself.  Features like connected components or context would be beneficial to some, but those not using the features would have to pay the performance price.  The PR is to enable app creation with inversion of control -- empowering users to add the features themselves.

## Details
```jsx
import { h, app } from 'hyperapp';
```
With this PR these would continue to work exactly as they do today; however, a new `hyper` function would also be available.
```jsx
import { h, hyper } from 'hyperapp';
```
The `hyper` function takes a `parseNode` function and returns an `app` function.
The `parseNode` function has the following signature:
```jsx
const parseNode = (node, parent, globalState, wiredActions) => /* node */
```

✳️ **EDIT:** _The `hyper` function has been replaced with an overloaded `app` function.  Example:_
```js
app(parseNode)(state, actions, view, document.body);
```
✳️ **EDIT:** _To be clear, the `parseNode` functions are not supplied by HyperApp, but instead developed by the community.  Below are a few examples I created just to show some of the capabilities._

### Example: App supporting Context
```jsx
const { h, hyper } from 'hyperapp';
// Create the app with a custom node parser
const app = hyper(nodeParserWithContext);
// Thanks to nodeParserWithContext every component now receives context!
const Component = (props, children, context) => <div />;
app(state, actions, view, document.body);
```
Want to see it in action?  Check out this [CodePen](https://codepen.io/jason-whitted/pen/BYVjmb).

### Example: Using Context to create Provider/connect (like redux)
Building upon the previous Context example, we can easily create a `Provider` component and `connect` HOC.

Want to see it in action?  Check out this [CodePen](https://codepen.io/jason-whitted/pen/LQrGam).

### Example: App supporting Connected Components
```jsx
const { h, hyper } from 'hyperapp';
// Create the app with a custom current parser
const app = hyper(nodeParserWithCurrent);
// Thanks to nodeParserWithCurrent every component now receives a current object
// The current object has getState() and getActions() methods
const Component = (props, children, { getState, getActions }) => <div />;
app(state, actions, view, document.body);
```
Want to see it in action?  Check out this [CodePen](https://codepen.io/jason-whitted/pen/OQENPL).

### Example: App that combines children into props
```jsx
const { h, hyper } from 'hyperapp';
// Create the app with a custom parser
const app = hyper(nodeParserWithChildrenInProps);
// Thanks to nodeParserWithChildrenInProps every component now only receives one props object
const Component = ({ children, ...other }) => <div>{children}</div>;
app(state, actions, view, document.body);
```

Want to see it in action?  Check out this [CodePen](https://codepen.io/jason-whitted/pen/GQGZqV).

### Example: Error Boundaries
```jsx
const { h, hyper } from 'hyperapp';
// Create the app with a custom error boundary node parser
const app = hyper(nodeParserWithErrorBoundary);
// Thanks to nodeParserWithErrorBoundary components that throw errors can be handled
const Throw = (props, children) => { throw new Error('Boom!'); }
app(state, actions, view, document.body);
```

Want to see it in action?  Check out this [CodePen](https://codepen.io/jason-whitted/pen/GQGZyg)

## Conclusion
This PR should have no negative performance impact; however, it should be able to satisfy many of the following issues / PRs: #388, #615, #601, #569, #604, etc.

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
@etalisoft I don't want to export a new function. What other options do we have?

**Comment by JorgeBucaran** [comment]
> @etalisoft The PR is to enable app creation with inversion of control -- empowering users to add the features themselves.

Too much power leads to option paralysis, so while I like this, it's not for Hyperapp. I would be interested in exploring adding only one more feature to Hyperapp, for example, a "context" feature like React's.

- https://github.com/hyperapp/hyperapp/pull/604#issuecomment-367552428

**Comment by etalisoft** [comment]
> @JorgeBucaran I don't want to export a new function. What other options do we have?

Wow, you read that wall-of-text in 2 minutes? 

A couple of options I can think of:

- An optional 5th parameter to `app`
  `app(state, actions, view, document.body);`
- If the first parameter is a function then apply inversion of control
  `app(parseNode)(state, actions, view, document.body);`

**Comment by JorgeBucaran** [comment]
@etalisoft For starters, let's make a few changes. Extract all the functions from the app body, to the top level of the module/file and rename <samp>hyper</samp> to <samp>createApp</samp>.

Also, I am still not sure if I want to go with #606 or not. Perhaps consider answer the questions you were asked on that issue first.

**Comment by JorgeBucaran** [comment]
> @etalisoft If the first parameter is a function then apply inversion of control...

I think this is an acceptable compromise. What do you think? @okwolf @zaceno

**Comment by etalisoft** [comment]
> @JorgeBucaran Also, I am still not sure if I want to go with #606 or not. Perhaps consider answer the questions you were asked on that issue first.

#606 is @frenzzy's PR.  I don't think I have any pending questions.  I did piggyback off of his change, though, because it moved the node function invocation out of the `h` function and into the `app` function.

**Comment by JorgeBucaran** [comment]
@etalisoft You are right, my bad. Those are @frenzzy's pending questions.

**Comment by JorgeBucaran** [comment]
@etalisoft Sorry, but could you remove @frenzzy's lazy components from this PR?

**Comment by etalisoft** [comment]
> @JorgeBucaran could you remove @frenzzy's lazy components from this PR?

Previously the `h` function invoked all components BEFORE they were passed to the `app` function.
```js
export function h(name, attributes /*, ...rest*/) {
  ...
  return typeof name === "function"
    ? name(attributes || {}, children) // <-- this line executes outside of the app context
    : {
        nodeName: name,
        attributes: attributes || {},
        children: children,
        key: attributes && attributes.key
      }
}
```

The `h` function immediately invokes child components outside of the context of the `app`.  However the `parseNode` function needs to be ran within the scope of the `app`.  

The lazy-loaded solution instead returns an object with the nodeName remaining as a function.
```js
export function h(name, attributes /*, ...reset */){
  ...
  return {
    nodeName: name,  // <-- Components remain as functions until the app processes them
    attributes: attributes || {},
    children: children,
    key: attributes && attributes.key
  }
}
```

The lazy-loading was the gateway to allow this to work.  This is similar to how [React's](https://reactjs.org/docs/shallow-renderer.html) and [Enzyme's](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md) shallow rendering works.

**Comment by zaceno** [comment]
>  Some features need to be implemented inside app itself. 

This sentiment I agree with. Actually, more than parseNodes, I'd like the ability to inject middleware (or replace) how the actions are wired.

So regardless of parseNodes, I think this discussion is interesting. Personally I wouldn't mind exporting another function -- especially If we want to offer multiple other injection points in the future. `app()` can only be overloaded so far.

But about parseNodes:

So the idea is to use it like this:

```js

const myParseNodes = node => {
   ...
   return parsedNode
}
...
app(parseNodes)(state, actions, views, container)

```

Other than the terser code, what's the benefit over using a HOA? Like this:

```js
const myParseNodes = node => {
  ...
  return parsedNode
}

const myApp = app => (state, actions, originalView, container) => {
  const myView = (state, actions) => {
    return myParseNodes(originalView(state, actions))
  }
  return app(state, actions, myView, container)
}


myApp(app)(state, actions, view, container)
```

**Comment by okwolf** [comment]
>> @etalisoft If the first parameter is a function then apply inversion of control...
>
> @JorgeBucaran I think this is an acceptable compromise. What do you think? @okwolf @zaceno

Sounds fine to me. If we refactor the existing `app` to reuse this same path it shouldn't add too much to our footprint either.

**Comment by jorgebucaran** [comment]
@etalisoft Thanks to your work on this and your other work with connected components we figured out lazy components and #606 is now merged into master and will be published in the upcoming 1.2.0. I think that what you are proposing here is super interesting, but not aligned with Hyperapp extreme minimal goals. Good job anyway! 👋

**Pull request closed without merging**
