### PR TITLE
Converted remaining vars to const or let.

### PR DESCRIPTION
**Pull request by rbiggs**
For better block scoping, converted remaining occurrences of var to
const or let where reassignment was necessary.

### CODE REVIEW

**Comment by rbiggs** [comment]
Nice job in converting app.js to ES6 syntax. 👍 I noticed there were a lot of vars still hanging around. For better block scoping in converted the remaining ones to const unless reassignment was necessary.   This builds and passes your jest test. I also dropped it into a local copy of your examples and they all work.

**Comment by jbucaran** [comment]
Hi @rbiggs! Thank you, but this is the same as https://github.com/hyperapp/hyperapp/pull/42.

**Comment by tunnckoCore** [comment]
This won't happen using Rollup + Buble. But there another thing would happen that will increase the bundle with 50-100 bytes (because the `route` function).

**Comment by rbiggs** [comment]
Closing

**Pull request closed without merging**
