### PR TITLE
Add a test to make sure JSX fragment support won't be broken in the future

### LINKED ISSUE #530: Fragment node type to support <></> JSX syntax?
```js
const view = <>
  <h1>{state.count}</h1>
  <button onclick={actions.down}>-</button>
  <button onclick={actions.up}>+</button>
</>
```
to avoid writing commas in jsx:
```js
const view = [
  <h1>{state.count}</h1>,
  <button onclick={actions.down}>-</button>,
  <button onclick={actions.up}>+</button>,
];
```

refs:
- [babel-plugin-transform-react-jsx#pragmaFrag](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx#pragmafrag)
- [Fragments in React.js](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html)

by the way, returning an array of elements from root view leads to `<undefined></undefined>` in DOM but nested views are rendered as expected

### PR DESCRIPTION
**Pull request by frenzzy**
Looks like Hyperapp already support JSX Fragments, need to just add docs how to use them:

```js
import { h, app } from 'hyperapp'
const Fragment = (_, children) => children

const view = () => (
  <main>
    <Fragment>
      <h1>A</h1>
      <h1>B</h1>
    </Fragment>
  </main>
)

app({}, {}, view, document.body)

console.log(document.body.innerHTML)
// => <main><h1>A</h1><h1>B</h1></main>
```

Demo: https://codepen.io/frenzzy/pen/WMZMVb?editors=0010

To use `<></>` syntax, use the following .babelrc config:
```js
{
  "plugins": [
    ["@babel/plugin-transform-react-jsx", { "pragma": "h", "pragmaFrag": "Fragment" }]
  ]
}
```
and your view may look like this:
```js
const view = () => (
  <main>
    <>
      <h1>A</h1>
      <h1>B</h1>
    </>
  </main>
)
```

After #591 we will be able to use fragments as a root node:
```js
const view = () => (
  <>
    <h1>A</h1>
    <h1>B</h1>
  </>
)
```

refs:
- [babel-plugin-transform-react-jsx#pragmaFrag](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx#pragmafrag)
- [Fragments in React.js](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html)

Closes #530

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
Fragments are about treating a tuple or array of elements/nodes as a single keyed item, this is just a clever way to fake it out. The big deal about fragments is, in my opinion, is stuff like:

```jsx
<Fragment key={key}><A/><B/></Fragment>
```

We may have this at some point in the future, but first I need to fix #499.

**Comment by sergey-shpak** [comment]
@frenzzy hey, looks like this approach doesn't work with lazy components
https://codepen.io/anon/pen/rKRxYd

**Comment by Swizz** [comment]
@sergey-shpak Lazy Components like the View root can't return an array. A root element is always required.

See #695

**Comment by sergey-shpak** [comment]
@Swizz thanks!

**Pull request closed without merging**
