### PR TITLE
Remove modules from docs

### PR DESCRIPTION
**Pull request by okwolf**
This part of the docs references functionality that has been removed.

### CODE REVIEW

**Comment by willin** [comment]
@JorgeBucaran  why removed?

in router plugin

```js
const state = {
  location: location.state
}

const actions = {
  location: location.actions
}
```

still use so

**Comment by JorgeBucaran** [comment]
Would be nice to have docs about modules in general.

**Comment by okwolf** [comment]
@JorgeBucaran I realized that since we moved from an object to positional arguments for `app` it's now tougher to add this kind of functionality with an HOA. Any options would really have to be passed to the HOA:
```
withModules({
  // ...
})(app)(state, actions, ...)
```

Instead of being available in the props like we used to have long ago:

```
withModules(app)({
  state,
  actions,
  modules: {
    // ...
  },
  // ...
})
```

**Comment by JorgeBucaran** [comment]
@okwolf 🤔 I am pretty sure I can write a function that accepts `app` as an argument and returns a function that takes whatever object or number of objects, e.g., { state, actions, ... }.

**Comment by okwolf** [comment]
> @JorgeBucaran 🤔 I am pretty sure I can write a function that accepts app as an argument and returns a function that takes whatever object or number of objects, e.g., { state, actions, ... }.

You could, but it wouldn't play nicely with any other HOAs that rely on a different signature for `app`. You'd have fragmentation of tools that worked for each different style. I personally prefer the object form because it has maximum flexibility and futureproofing.

**Comment by JorgeBucaran** [comment]
@okwolf I see what you are saying, but IMO making HOAs easier to write does not warrant changing the core. You could also make it `app(state, actions, view, modules, container)`.

**Comment by JorgeBucaran** [comment]
Then make modules come last? I know, not so nice. Then, maybe HOAs will need to be programme defensively? TBH I don't think I'd want to use an HOA for modules, but instead something like [combineModels](https://gist.github.com/JorgeBucaran/4dfa567e38ca222c25c46184b3a5df99).

**Comment by okwolf** [comment]
@JorgeBucaran that object `combineModels` returns would spread very nicely into `app` if only it took an object instead 😜

**Comment by JorgeBucaran** [comment]
> is writing higher-order apps a hack or a supported extension mechanism?

I wouldn't call it a hack, but I don't want to say it's a supported extension mechanism either. The term "support" is slightly odd since Hyperapp is doing nothing to prevent or promote creating HOAs. I think HOAs are not frowned upon, but they should be used sparingly.

> If the former, then we need a new way to support extending Hyperapp like we've previously had with mixins, events, hooks, etc...

This could be discussed.

**Comment by willin** [comment]
i'm trying to make a i18n plugin, and now wondering about how to create a module named i18n?

**Comment by okwolf** [comment]
@willin on the subject of i18n, make sure you read our previous issue: #397.

**Comment by willin** [comment]
yep but it's not so graceful. and i want to write my own.

**Comment by JorgeBucaran** [comment]
@willin Just create it? :)

**Comment by willin** [comment]
the point is not i18n,

is how to create a sub module

**Comment by willin** [comment]
if i figure it out... perhaps it can be i18n, ui-framework, visualization or so on...

**Comment by willin** [comment]
In source:

```js
// example
export const state = {
   lang: '',
   langs: []
}

export const actions = {
   setLocale: (lang) => () => ({lang})
}
```

When use:

```js
const {state} = require('hyperapp-i18n');
// state.js
export default {
   // blabla
   i18n: state
}
```

```js
const {actions} = require('hyperapp-i18n');
// actions.js
export default {
   // blabla
   i18n: actions
}
```

then how to use state/actions?

```js
const main = app(state,actions,view,document.body);

// is this right?
main.i18n.setLocal('en-US');
```

```js
// is this right?
const view = (state, actions) => (
   <div>{stat.i18n.lang}</div>
);
```

**Pull request merged**
