### PR TITLE
[RFR] Documentation structure update

### PR DESCRIPTION
**Pull request by eschaefer**
Follows-up on the talk in https://github.com/hyperapp/hyperapp/issues/452

While this looks like a lot of changes, it is really just moving markdown files around. I have not changed the content of the documentation. An easier way to browse the changes would be to look at [how the files are structured here](https://github.com/eschaefer/hyperapp/tree/feature/docs-update/docs). 

screen shot 2017-12-20 at 00 20 02

The purpose of the restructuring is so we can autogenerate "nice" documentation for the website in a standardized "gitbook" kind of way. A sneak peek at how that would look can be [found here](https://temp.deadhare.com/docs/).

**Note**
The documentation would be grabbed as a zip file from the website repo, and then passed along to a [build script](https://github.com/eschaefer/website-1/blob/feature/docs/package.json#L27). A different PR will be opened in the website repo after this one here is merged.

### CODE REVIEW

**Comment by selfup** [comment]
If you use the Octo-Git extension...no work needs to be done on our end 😂 

somethinglikethis

**Comment by eschaefer** [comment]
@selfup yep that's what I use myself :)

**Comment by JorgeBucaran** [comment]
Hi @eschaefer! I finally had a look at this and just merged it! Thanks 🎉

**Comment by JorgeBucaran** [comment]
@eschaefer I'd like to remove the SUMMARY.md file, it's confusing.

**Comment by Swizz** [comment]
`SUMMARY.md` will help to create the navbar, isnt it ?

**Comment by JorgeBucaran** [comment]
@Swizz Not sure, but nothing that can't be fixed in a build script before generating the documentation. Actually, if you look at the diff between SUMMARY and README, the only difference is the SUMMARY has one line at the top that links to the README, that's it.

**Comment by eschaefer** [comment]
> @eschaefer I'd like to remove the SUMMARY.md file, it's confusing.

Yeah this can definitely just be generated by the docs build script. Only needed for the reason @Swizz mentioned.

**Comment by JorgeBucaran** [comment]
@eschaefer I also noticed that you didn't change header size in subsections. I would prefer to start every own section with a `#` and not a `##` as they tend to nest up quickly.

**Pull request merged**
