### PR TITLE
code split for better maintenance

### PR DESCRIPTION
**Pull request by uxitten**

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
Thank you, @uxitten! That's a very nice code break up, but I am not interested in doing this. I am fine with one file to rule them all. Cheers!

**Comment by uxitten** [comment]
ok

**Comment by lukejacksonn** [comment]
@uxitten this is really cool to see, you must have learnt a hell of a lot about hyperapp by now!

**Comment by selfup** [comment]
Agreed with @lukejacksonn 😄 

Thanks for the effort 🎉

**Comment by JorgeBucaran** [comment]
@uxitten I am sorry I offered too little explanation. FWIW it's not the first time it has been proposed or similar PRs have surfaced. It's also on the [contribution guidelines](https://github.com/hyperapp/hyperapp/blob/master/CONTRIBUTING.md#style).

> ### Style
> - Hyperapp is written in ES3. Please don't create an issue asking us to rewrite it in ES6 or TypeScript.
> - We prefer keeping all the moving parts inside as few files as possible. We don't have plans to break up the library into smaller modules. If you are looking for a Virtual DOM implementation without Hyperapp's built-in state management check out Picodom.

👋

**Comment by uxitten** [comment]
thank's @lukejacksonn and @selfup

**Comment by uxitten** [comment]
@JorgeBucaran good ok

**Pull request closed without merging**
