### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by JorgeBucaran**
## Summary
This PR contains probably my last major changes to core before 1.0. After I merge this, I'll proceed to merge #498 and release 0.18.0 so those using hyperapp right now can update to the latest and not need to wait until 1.0, which should happen in the coming weeks.

## Boilerplate

You can reduce setup boilerplate with a function that maps your props to a model.

```jsx
const { state, actions } = mapPropsToModel({
  counter, mouse, keyboard, location
})
```

**OR**

```jsx
const { state, actions } = mapPropsToModel({
  count: 0,
  down: () => state => ({ count: state.count - 1 }),
  up: () => state => ({ count: state.count + 1 })
})
```

### Counter.js

```jsx
import { h, app } from "hyperapp"

const state = {
  count: 0
}

const actions = {
  down: () => state => ({ count: state.count - 1 }),
  up: () => state => ({ count: state.count + 1 })
}

const view = (state, actions) => (
  <main>
    <h1>{state.count}</h1>
    <button onclick={actions.down}>-</button>
    <button onclick={actions.up}>+</button>
  </main>
)

const main = app(state, actions, view, document.body)
```

### Counter.ts

```tsx
import { h, app, WiredActions } from "hyperapp"

namespace Counter {
  export interface State {
    count: number
  }

  export interface Actions {
    sub(): State
    add(value: number): State
  }

  export const state: State = {
    count: 0
  }

  export const actions: WiredActions<State, Actions> = {
    sub: () => state => ({ count: state.count - 1 }),
    add: (value: number) => state => ({
      count: state.count + value
    })
  }
}

const main = app<Counter.State, Counter.Actions>(
  Counter.state,
  Counter.actions,
  (state, actions) => <div>{state.count}</div>,
  document.getElementById("app")
)
```

### CODE REVIEW

**Comment by okwolf** [comment]
@JorgeBucaran isn't your `Counter.js` example missing the `app` call?

```js
app(state, actions, view, document.getElementById("app"))
```

Also, I'd like to mention that one of the things I liked most about Hyperapp when I first came across it was passing the parameters to `app` as a single object. Then we moved the `root`/`container` to a separate argument.

Now it looks like we've swung to the other extreme of spreading the parameters out to their own arguments. I've probably been biased by [Rich Hickey](https://youtu.be/2V1FtfBDsLU?t=46m51s), but I much prefer named arguments à la:

```js
fn({
  state: a,
  actions: b,
  view: c
})
```

versus positional semantics:

```js
fn(a, b, c)
```

Yes, you can always look it up in the docs, but with the object approach, a dev build of Hyperapp could actually know that a user got the name of something wrong, instead of crashing and burning in weird ways by trying to call your `actions` as the `view` because you got the order of the arguments wrong. Not to mention the names would be preserved even in a minified build you were unlucky enough to have to debug in production without source maps.

**Comment by selfup** [comment]
Are we ditching `model` already from `0.17.1`?

Just wondering

**Comment by zaceno** [comment]
What does app return now? Anything?

**Comment by okwolf** [comment]
> @zaceno What does app return now? Anything?

Pretty sure we are back to `app` returning `actions` again: https://github.com/hyperapp/hyperapp/blob/1.0.0/src/index.js#L40

**Comment by zaceno** [comment]
@okwolf thanks, good on you for checking the code! Wonder why I didn't do that?! 😆 Anyway, so my warning holds true: no async access to current state, except via actions (which may not always be desirable)

**Comment by okwolf** [comment]
@zaceno state getters are dead, long live state getters.

**Comment by zaceno** [comment]
For example: no access to *current* state in `onremove` handlers. Or in `setTimeouts` called from event handlers.

**Comment by JorgeBucaran** [comment]
@okwolf 

```js
app(state, actions, view, container)
```

**Comment by okwolf** [comment]
> @zaceno Oh I totally forgot about the `{ getState: _ => state => state, ...}` hack. That probably works still.

That was what I meant by state getters.

**Comment by JorgeBucaran** [comment]
@selfup Ditching models as a built-in concept, because you can easily do it yourself.

```jsx
const model = {
  state: { ... },
  actions: { ... }
}

const { state, actions } = model

app(state, actions, view, container)
```

**Comment by JorgeBucaran** [comment]
> @okwolf ...because you got the order of the arguments wrong.

I guess one could get the order wrong, specially when using Nodepad or TextEdit.

Remember you call the app function only once, so if you make a mistake, you fix it only once. And if you prefer named props, then write an HOA that takes your props and calls the app function for you! 🎉

**Comment by JorgeBucaran** [comment]
@zaceno `getState` is not a hack. And:

> For example: no access to current state in onremove handlers. Or in setTimeouts called from event handlers.

`getState` or create a vnode wrapper in the view function.

**Comment by selfup** [comment]
Ok thanks for clearing that up!

**Comment by okwolf** [comment]
> @JorgeBucaran And if you prefer named props, then write an HOA that takes your props and calls the app function for you!

That is true. This was my only concern about the API, and I don't feel strongly enough about it to fight passionately for it.

I think we just need docs updates and this will be good to merge, right?

**Comment by JorgeBucaran** [comment]
And types!  💪🔥

**Comment by okwolf** [comment]
> @JorgeBucaran And types! 💪🔥

So should #498 merge into this branch instead of master then? 🤔

**Comment by JorgeBucaran** [comment]
I'll merge here first, then merge @Mytrill's PR and finally work a bit more on the types myself as I need some changes, some of which are not so technical, but "artistic" and don't want to bother @Mytrill! 😅💦

**Comment by JorgeBucaran** [comment]
@zaceno I updated the example to illustrate the app returns an object I'm going to call `main`. This object represents your app and it's how you communicate with it from the "outside". It's nothing but the good old `actions`, **wired** to the state-update—view-render mechanism. tl;dr app returns your actions.

```js
const main = app(state, actions, view, document.body)
```

**Comment by zaceno** [comment]
@JorgeBucaran 
>  create a vnode wrapper in the view function and use the lifecycle.

If you're talking about defining getters in the view, that's precisely what *doesn't* work for `onbeforeremove`,  `onremove`, and inside `setTimeout` called from event handlers (for example) -- because by the time they're called, any state they need may be outdated. 

One could solve it by maintaining an up to date synced copy of the state you might need to access async (maybe that's what you were talking about?) but that's obviously far from ideal.

As you mentioned, `getState` works too, but that's *also* not ideal, because that causes a run through merge, and a repaint for no good reason (all you wanted was to read the state)

So it's not an unsolvable problem. But I think that whoever else encounters this class of problems (including @JorgeBucaran, when and if it happens), will feel that the available solutions are unsatisfactory.

**Comment by JorgeBucaran** [comment]
@zaceno Sorry, what are you talking about? I am interested in this problem, but here seems like an odd place to discuss this, that's maybe why I don't understand what you are saying.

**Comment by zaceno** [comment]
@JorgeBucaran Yes this is an odd place, I agree. 😄 - It's the same thing I've been talking about before on slack, but it probably deserves a proper issue, so I will open one.

**Pull request merged**
