### PR TITLE
Composable app

### PR DESCRIPTION
**Pull request by AutoSponge**
addresses https://github.com/hyperapp/hyperapp/issues/148
technique for avoiding problems found in https://github.com/hyperapp/hyperapp/issues/117
may also solve https://github.com/hyperapp/hyperapp/pull/141 if `isSameNode` is used by virtual node, requires test

# Explanation
#151 is about trying to make apps smaller and with single-purpose. Then, using composition and communication (not enforced by the framework), construct your goal.

In my [example](https://gomix.com/#!/project/picayune-postbox), I created a self-contained `app` called `slide`. The `slide` component exports a create method. 

Because `app()` now returns its root and `h()` roots are upgraded to DOM nodes, the `main` app that composes over the `slide`s only has to worry about its `model`--the list of slides. Some additional state was added to "control" when to add/remove/transition slides, but that's gravy to demonstrate the extensibility of the pattern.

In this example, I used shared knowledge of an event namespace to communicate from `main` to the `slide`s. if 2-way communication was needed, the `slide` app could trigger a `register` event that passes an event emitter as data to the `main` and any apps that are composing over `main`.

When passing events to parents, use bubbling (capture=false) so that propagation can be stopped by a parent. When passing events "down" the stack, make sure the composed component uses capturing to get the event. These will process before any "upstream" apps receive the event.

### CODE REVIEW

**Comment by AutoSponge** [comment]
I'm working on the example using this version.

**Comment by jbucaran** [comment]
@AutoSponge Thanks! I've left a few notes, let's discuss :)

**Comment by AutoSponge** [comment]
I made a thing based on the previous "problem" example in #117. I will need to add some tests, but please evaluate these changes to see if they fit the overall need.

[example](https://gomix.com/#!/project/picayune-postbox)

Things learned:
- If the `app` is lazy (passed a `root`) we can return that root. But if using dynamic `root`, we can't return because the root isn't created until the DOM is ready. This might be able to change with either a promise or by creating the root element before the DOM is ready and mounting it on DOMready. This wasn't changed because it wasn't needed for this example.
- There seems to be a bug in `patch` when `parent.childNodes[index]`  doesn't exist (needs test).
- I learned how to make this slider thing!

**Comment by dodekeract** [comment]
> There seems to be a bug in patch when parent.childNodes[index] doesn't exist (needs test).

You could add a watch expression for that in the developer tools/debugger.

**Comment by AutoSponge** [comment]
This is done but if it comes after the "keys" PR, it may need to be reworked.

**Comment by AutoSponge** [comment]
This was a small change that supported several use cases. But master is changing constantly and I don't have time to keep rebasing this. Let me know when you want it and I'll fork again.

**Pull request closed without merging**
