### PR TITLE
save bytes by re-using variable names

### PR DESCRIPTION
**Pull request by lazarljubenovic**
It's all function scope with `var` anyway.

### CODE REVIEW

**Comment by jbucaran** [comment]
@lazarljubenovic I think this doesn't actually end up saving any bytes in the compressed bundle. If you are developing hyperapp locally, you can run the `build` script and compare the bundle size. Then post here the before and after.

**Comment by lazarljubenovic** [comment]
Minified: 3605 to 3595
Gzipped: 1636 to 1637.

Gzip is a bitch. :unamused:  

A problem with gzip is that it's not really easily predictable how it wil behave. Maybe two separate changes both increase gzip filesize, but together they decrease it (if there are repeating parts in them).

**Comment by lazarljubenovic** [comment]
Now gzip stays the same, but minified version gets from 3605 down to 3596. Do we care for this or only gzip? It doesn't make code any less easier to read imo.

**Comment by jbucaran** [comment]
> Do we care for this or only gzip?

I'd say gzip.

**Comment by lazarljubenovic** [comment]
No need for this since gzipped version doesn't improve.

**Pull request closed without merging**
