### PR TITLE
Support for non-object slices

### PR DESCRIPTION
**Pull request by frenzzy**
An alternative solution for #609 and #512

- It allows to write more simple code as described in this comment: https://github.com/hyperapp/hyperapp/pull/609#issuecomment-367253627
- It allows to change data type of a slice or easily override/remove it
- It makes custom merge method unnecessary #532 (I hope)

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
@frenzzy Can I also do something like this?

```jsx
const state  = 0
const actions = { up: () => state => state  + 1 }

app(state, actions, view, container)

**Comment by Swizz** [comment]
Only curiosity, not required : 
The #512 side effect is still working ? 

```jsx
const state = {
  counts: [{
    count: 0
  }]
}

const actions = {
  counts: [{
    up: () => state => ({ count: state.count + 1 })
  }]
}

const view = (state, actions) => (
  <div>
   {state.counts[0].count}
  </div>
)

const main = app(state, actions, view, document.body)

main.counts[0].up()
```

**Comment by frenzzy** [comment]
@JorgeBucaran this is possible only if change this line:
https://github.com/hyperapp/hyperapp/blob/8b501cea26179e223c0fadf188e8bcad5219b442/src/index.js#L35
because `clone` converts everything to an object

**Comment by JorgeBucaran** [comment]
@frenzzy Gotcha, not worth it.

**Comment by frenzzy** [comment]
@Swizz no, actions nested to arrays are still not supported.
But you can rewrite the example:
```js
const state = {
  counts: [
    { count: 0 }
  ]
}

const actions = {
  counts: {
    up: (index, value) => state => state.map(
      (slice, idx) => idx === index ? { count: slice.count + value } : slice
    )
  }
}

const view = (state, actions) => (
  <div>
    {state.counts[0].count}
  </div>
)

const main = app(state, actions, view, document.body)

const counterIndex = 0
const upValue = 100
main.counts.up(counterIndex, upValue)
```

**Comment by jason-whitted** [comment]
@frenzzy Your example won't actually work as illustrated in [this CodePen](https://codepen.io/jason-whitted/pen/wyjRgO?editors=0010).

Currently the actions only accept one value, because of this block of code:
```js
  function wireStateToActions(path, state, actions) {
    for (var key in actions) {
      typeof actions[key] === "function"
        ? (function(key, action) {
            // The function is created only supporting the single parameter 'data'
            actions[key] = function(data) {
              // action is then called with only one argument
              if (typeof (data = action(data)) === "function") {
                data = data(get(path, globalState), actions)
              }
              ...
```

**Comment by frenzzy** [comment]
@jason-whitted the issue you found is not related to the current PR, see #619

**Comment by okwolf** [comment]
I don't really understand how the primitive type support is an improvement since it lets you treat the values as objects for nesting actions, which means inconsistent state/actions shape.

For arrays, I have the same concerns as I did before: https://github.com/hyperapp/hyperapp/pull/512#issuecomment-354497710

**Comment by frenzzy** [comment]
@okwolf this is not about nested actions, but about an ability to write more simple actions for primitive types. See https://github.com/hyperapp/hyperapp/pull/609#issuecomment-367253627 how it simplifies todo example.
```js
const state = {
  name: "",
  age: 0
}
const actions = {
  setName: value => { name: value }
  setAge: value => { age: value }
}
actions.setName("Jhon")
actions.setAge(18)
```
vs
```js
const state = {
  name: "",
  age: 0
}
const actions = {
  name: { set: value => value }
  age: { set: value => value }
}
actions.name.set("Jhon")
actions.age.set(18)
```

**Comment by JorgeBucaran** [comment]
I find this feature rather confusing. It's easier if we just deal with objects.

**Comment by okwolf** [comment]
> @frenzzy this is not about nested actions, but about an ability to write more simple actions for primitive types

Perhaps we are in agreement that nested actions shouldn't be used for primitive types, but that's exactly what I see in this proposal. The actions for `name` and `age` are nested in an object, which is not the shape of the state they update. I think we might be using two different definitions of "simple" though.

How exactly is someone to tell if `actions.name` is for a primitive type or a state slice? I understand that returning a non-object from an action today can break things, but at least there's only one valid way to return the new state once you learn how to use it everywhere. What explosions can we expect in a world where there are multiple valid options and someone accidentally returns a partial state object where a primitive was supposed to be? 💣 

And what exactly are we gaining from this? IMHO `actions.setName` is _not_ a bigger burden to use than `actions.name.set`.

**Comment by Swizz** [comment]
So the complementary of this PR should be to remove partials ?

@zaceno and I were discussing about this feature some weeks ago.
One of the benefits of this feature is to make the user life a litle bit easier. And every one here know I am on this side since the beggining.

But, I am not on the same page regarding `actions.setName`. I am using a `set` actions in each slice, and I use objects to tell the key to set, with bonus to be able to set multiple once `actions.set({ name: "Jhon })`

**Comment by JorgeBucaran** [comment]
@Swizz Sorry, but what are partials? 😄

**Comment by Swizz** [comment]
> To update the state, an action must return **a partial state object**

I took the bad habit (maybe ?) to call them partials.

**Comment by JorgeBucaran** [comment]
No problem. If the complement of this PR is to remove partials on another one, then I don't see myself merging this ever. I think for the looks of it this is probably going to be another wontfix.

**Comment by frenzzy** [comment]
When I opened this PR the idea was to allow to easily reduce slices with primitive types [like in Redux](https://redux.js.org/basics/reducers#source-code) and mostly to make work with arrays simpler.

I absolutely agree with @okwolf and @JorgeBucaran points. This feature may introduce confusion and misuse and this feature is not worth it.

So, should we just close this PR or will wait for more opinions?

**Comment by Swizz** [comment]
Or open a RFC as an issue to gather feedbacks and wish about this feature ?

**Comment by JorgeBucaran** [comment]
I say let's leave it open for a bit more to collect more feedback.

**Pull request closed without merging**
