### PR TITLE
Small fix to typescript definition of h function

### PR DESCRIPTION
**Pull request by Mytrill**
The h function may accept arrays of Component | string | number.

### CODE REVIEW

**Comment by Mytrill** [comment]
Hum, why does it want to re-merge commits from my previous pull request?!

**Comment by JorgeBucaran** [comment]
@Mytrill Not sure! Maybe you can push -f to your branch or create a new PR? 🤔

**Comment by Mytrill** [comment]
Looks like it is because my fork is 5 commits ahead of master: https://github.com/Mytrill/hyperapp
I assume I did something wrong when merging the fork with master :/
I'll have a look at it later today and I will create a new PR at this point.

**Comment by JorgeBucaran** [comment]
@Mytrill Sure, no worries! If you can't fix this one, just close it and open a new one. It's all good.

**Pull request closed without merging**
