### PR TITLE
Default mixin.events to empty object

### PR DESCRIPTION
**Pull request by sghall**
Cool library. Just taking a look at the source.  I don't think this matters from a code execution standpoint (you'll get an empty array of keys with [] or {}) but it caused me to do a double take.  I was looking at the logger mixin source https://github.com/hyperapp/logger/blob/master/src/index.js#L16 where events is an object to see how it gets handled and spotted this.

### CODE REVIEW

**Comment by okwolf** [comment]
I'm ok with this. Although `Object.keys({}) == Object.keys([])` the former probably makes more sense than the latter.

**Comment by sghall** [comment]
Suppose to be totally consistent on this would change this line too for the actions...
https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L33

Just makes it clearer you're expecting an object. If you want to add that to the PR or I can add it tomorrow.

**Comment by JorgeBucaran** [comment]
Hi @sghall,

Looks good to me. Can you also change: 
- https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L33 ? 🙇 

I'll merge then.

**Comment by sghall** [comment]
Done.  This one is ready to go.

**Comment by JorgeBucaran** [comment]
Thanks @sghall! 🎉

**Pull request merged**
