### PR TITLE
Docs Update

### PR DESCRIPTION
**Pull request by okwolf**
Did this in many parts in case any are not desired and should be reverted:
- ~~[Markdownlint](https://github.com/DavidAnson/markdownlint) to sanity check the content for consistency as part of the build~~
- Update inconsistent use of languages in code fences. If we want to pick one standard we could use `jsx` for all JavaScript code since it's a superset of `js`. For now I picked the one that fits closest based on content used.
- Some additional helpful links on Getting Started page.
- ~~Follow GitHub's [standard for the code of conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project).~~
- Some OCD changes where there were deviations in grammar, punctuation, and use of `inline code`.
- A warning about using `innerHTML`. See #360.

### CODE REVIEW

**Comment by jbucaran** [comment]
@okwolf Looks good.

Pet peeve: Don't split the CoC and CONTRIBUTION.md

**Comment by jbucaran** [comment]
2nd pet peeve: Remove markdown lint and .markdownlintrc.

**Comment by okwolf** [comment]
> @jbucaran Don't split the CoC and CONTRIBUTION.md

Do you disagree with https://opensource.guide/code-of-conduct? I noticed they also recommend linking it from CONTRIBUTING or README.

**Comment by okwolf** [comment]
@jbucaran reverted the Markdownlint changes.

**Comment by jbucaran** [comment]
My views on CoC are still very mixed. I originally added the CoC because there was a user trolling hyperapp, but since that did not stop the person I blocked them.

I don't think a CoC will make people suddenly behave well, and if it does, then I'd be wary of those people (but then how do you tell!) 

It's not as if humans need a moral code to be moral.

**Comment by jbucaran** [comment]
So, I'd say let's not have a CoC for now. If we find a need for it in the future, then we can add it.

**Comment by okwolf** [comment]
> @jbucaran So, I'd say let's not have a CoC for now. If we find a need for it in the future, then we can add it.

I reverted my changes for CoC.

**Comment by okwolf** [comment]
@jbucaran who else should we assign as reviewers?

**Comment by jbucaran** [comment]
Ref: https://github.com/markdownlint/markdownlint/issues/179

**Comment by jbucaran** [comment]
@okwolf Whoever wants to take a stab. I'll merge later today.

**Comment by jbucaran** [comment]
Thanks @okwolf! 💯🎉

**Pull request merged**
