### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anywhichway**
Added reference to jsxdirect for in browser JSX transpilation.

### CODE REVIEW

**Comment by selfup** [comment]
Looks like travis had a bad time pulling from npm:

```
$ npm install

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

https://travis-ci.org/hyperapp/hyperapp/jobs/397754853

I would `git commit --amend` and just change the commit message just slightly (update section about JSX in README)

See if that makes the builds pass (it should :smile)

🛩

**Comment by anywhichway** [comment]
@jorgebucaran Thanks. Just discovered a bug with jsxdirect, it requires quotes for attributes with {} (the opposite of the standard). So as not to pollute your site with a reference to a library that operates in a non-standard way, I will abort the pull request for now.

**Comment by jorgebucaran** [comment]
Thanks, @anywhichway. Do you think you'll be able to fix the bug?

**Comment by anywhichway** [comment]
Yes, probably this weekend

**Comment by anywhichway** [comment]
Fixed bug and did another pull request.

**Pull request closed without merging**
