### PR TITLE
#354 forward compatible prepare script

### LINKED ISSUE #354: Seems that we should use both `prepublish` and `prepare` for npm5 and npm3
As the title indicates, to be forward and backward compatible we should use both script keys.

```bash
hyperapp (master) $ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

### PR DESCRIPTION
**Pull request by selfup**
closes #354 

@jbucaran Let me know if this makes sense!

### CODE REVIEW

**Comment by selfup** [comment]
Also, why is CI not running? 🤔 

Is it because I assigned it to you?

**Comment by selfup** [comment]
Turns out @lukejacksonn mentioned that Travis and GitHub Webhooks have been in a weird state as of late. I have a friend who's Webhook based project is currently not working. So this should resolve on its own.

I'll amend this commit in a few hours to re-trigger a push event 👍

**Comment by jbucaran** [comment]
@selfup No idea, but LGTM.

When do you think it will be safe to remove `prepublish` from package.json?

**Comment by selfup** [comment]
That is a good question! I assume people contributing to hyperapp will be using npm5 but some might still use npm3. Then again you are the one that publishes 😂

**Comment by jbucaran** [comment]
@selfup Alright then, so let's keep it for a while.

**Pull request merged**
