### PR TITLE
Optimize isPrimitive

### PR DESCRIPTION
**Pull request by dodekeract**
Should be ~~the same speed~~ faster, ~~but 9~~ and 20 bytes less after minification/build.

### CODE REVIEW

**Comment by jbucaran** [comment]
@dodekeract Is this a new GitHub feature? I'm actually seeing the difference in bytes in the UI.

**Comment by dodekeract** [comment]
@jbucaran Quite sure that's just my commit message. :smile:

**Comment by jbucaran** [comment]
@dodekeract You are right 😆. Fail.

Yeah, this looks perfect.

**Comment by dodekeract** [comment]
@jbucaran Sorry if the last commit is too hacky. Was wondering if even less is possible. Turns out all 3 commits make it (9 + 11 + 9 =) 29 Bytes smaller.

**Comment by jbucaran** [comment]
@dodekeract Haha, yep, that's too hacky. Let's avoid that.

**Comment by jbucaran** [comment]
@dodekeract Let's go back to the original commit.

**Pull request merged**
