### PR TITLE
Add tests into workflow

### PR DESCRIPTION
**Pull request by maraisr**
This is still a work in progress, will ping you here when this is ready to role.

### CODE REVIEW

**Comment by jbucaran** [comment]
@maraisr I think I'm going to go with [tape](https://github.com/substack/tape) for tests.

**Comment by maraisr** [comment]
Tape doesn't offer a headless browser not unless you use `tape-run`, but even then using electron and speed were all just too cumbersome. Jest supports all this out of the box. And having Facebook behind it, means it's well supported. Don't think going with tape would be a good move.

**Comment by jbucaran** [comment]
@maraisr That sounds great, but what's the catch then? 🤔

**Comment by maraisr** [comment]
@jbucaran  catch? None! haha :100:

**Comment by jbucaran** [comment]
@maraisr Interesting. I don't think we'll introduce webpack though, so can you keep this PR focused on tests only? 🙏

**Comment by jbucaran** [comment]
@maraisr Think we can close this?

**Comment by maraisr** [comment]
Closed in favour of #52

**Pull request closed without merging**
