### PR TITLE
Update rollup and uglify versions

### PR DESCRIPTION
**Pull request by okwolf**
We're a whole major release behind on our UglifyJS version.

Minified size decreased from 3136 -> 3102 bytes however gzipped size increased from 1427 -> 1443 bytes? 😕

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
@okwolf Thanks, I'll have a look.

**Comment by JorgeBucaran** [comment]
@okwolf There is no good reason to upgrade uglifyjs that I know. Am I missing something? As soon as we decide to drop support for IE11, I'll drop uglifyjs altogether.

**Comment by JorgeBucaran** [comment]
@okwolf I can accept the other changes, including the simplified CLI flags.

**Comment by okwolf** [comment]
@JorgeBucaran I can accept the other changes, including the simplified CLI flags. If you can only change the uglify version back to how it was, then I'll merge this.

The changes to the CLI flags isn't compatible with our older version. Should we just merge the rollup update?

**Comment by JorgeBucaran** [comment]
Hmm I see.
> Should we just merge the rollup update?

Yeah.

**Comment by JorgeBucaran** [comment]
Nevermind. Let's upgrade. 🤷

**Comment by JorgeBucaran** [comment]
@okwolf Hopefully this will not break sourcemaps.

**Comment by whaaaley** [comment]
uglify3 has es6 stuff and a better cli interface

**Comment by okwolf** [comment]
> @JorgeBucaran Hopefully this will not break sourcemaps.

The output looked equivalent, but I didn't test it out in a real browser yet.

**Comment by JorgeBucaran** [comment]
@okwolf Well, could you?

**Comment by okwolf** [comment]
@JorgeBucaran verified sourcemaps are still working with the latest build from master 👍

**Pull request merged**
