### PR TITLE
Multiple app calls

### PR DESCRIPTION
**Pull request by frenzzy**
refs #533, #657, 7585a402626894cb1146044c77be42f177b885e2

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@frenzzy Why?

**Comment by frenzzy** [comment]
For Hot Module Replacement, just call `app` with new state/actions/view on the same node as parcel do.

**Comment by jorgebucaran** [comment]
Thanks, @frenzzy, but I don't understand why I'd want to merge this, but if you can properly explain why then I might be interested.

**Comment by frenzzy** [comment]
Oh.. looks like dynamic actions already works!
Demo: https://codepen.io/frenzzy/pen/NYvvKm?editors=0010
Nevermind then :blush:

**Comment by jorgebucaran** [comment]
🙃

**Comment by jorgebucaran** [comment]
@frenzzy A bit better.

```js
loadAction: () => state => {
  app(state, {...actions,
    double: () => state => ({ count: state.count * 2 })
  }, view, document.body)
```

Does this PR help improve the above and how? That would make sense.

**Comment by frenzzy** [comment]
Dynamic actions demo:
- master branch: https://codepen.io/frenzzy/pen/RMZxGY?editors=0010
- current branch: https://codepen.io/frenzzy/pen/MVvrQb?editors=0010

Steps:
1. Initial state: `10` => `<h1>10</h1>`
2. Click `load action` => `<h1>10</h1>`
3. Click `x2` => `<h1>20</h1>`
4. Click `+` =>
    - master branch: `<h1>11</h1>` // <= Wrong!
    - current branch: `<h1>21</h1>`

**Comment by okwolf** [comment]
Thanks for looking into this @frenzzy. Unfortunately, there are still more problems with multiple `app` calls as I've [previously written](https://github.com/hyperapp/hyperapp/issues/657#issuecomment-375777875).

To see one of the issues this doesn't solve take a look a this pen that simulates a second `app` call where each one wires up external events to call different actions (imagine a HMR scenario where that part of the code changed). This change does not help in this scenario as you can see if you switch the comments on the pen: https://codepen.io/okwolf/pen/vRJQpZ?editors=0010

Off the top of my head the only true solution I can think of would be to have some way of unwiring/stopping our previous `app` instance. Maybe attach this to the container element and call this if it exists when mounting a new `app`? 🤔

**Comment by jorgebucaran** [comment]
> Maybe attach this to the container element and call this if it exists when mounting a new app? 

Yeah, similarly to what I do in Ultradom.

**Comment by frenzzy** [comment]
> Off the top of my head the only true solution I can think of would be to have some way of unwiring/stopping our previous `app` instance.

But they are the different features:
- **An ability to call app multiple times** is the way how you can fire update your app with new state/actions/view without the actual stopping the app. You don't want to completely stop and run again the app because it is too much overhead. For example your components have to destroy and initialize instances of third-party libs when you have the opportunity to avoid it.
- **Stop/destroy/unmount** feature at the same time is needed to stop the application and allocate resources. Just removing a container DOM node is not enough because we need to destroy all instances and global event handlers by calling remove/destroy lifecycle events. The good news is that we can implement this feature in the user land, for example using a higher-order app approach. This feature also must remove all mounted DOM nodes from the container.

Suggested way to store VDom tree inside `element.node` sounds good to me and allows to easily implement unmount feature and helps multiple app calls to work properly. I am worried only about possible memory leaks with this approach because VDom tree also usually contains links to functions in VNode attributes.

**Comment by jorgebucaran** [comment]
We will not need to call app multiple times in 2.0, but we'll definitely want an unmount function or similar, eventually.

Since this code just deals with multiple app calls, I am going to close here as wontfix.

**Comment by frenzzy** [comment]
Should we also revert changes from this commit? 7585a402626894cb1146044c77be42f177b885e2

If multiple app calls are not supported, then changes from the commit just increase bundle size and useless for users.

**Comment by jorgebucaran** [comment]
That's also fixing an HMR bug, so I think I'll leave it.

**Comment by frenzzy** [comment]
@jorgebucaran the problem is HMR is not configured properly and by default it calls `app` multiple times on the same container. You are fixed events problem but do not fix actions and recycling problem from this PR.

In my mind if you want to support multiple app calls for default HMR, then do it properly or do not support at all. Am I wrong?

For example:
```js
let container = document.getElementById('app')

app(state, actions, view, container)

if (module.hot) {
  module.hot.dispose(() => {
    container.parentNode.removeChild(container)
  });

  module.hot.accept(function () {
    container = document.body.appendChild(document.createElement('div'))
    app(state, actions, view, container)
  });
}
```

**Comment by jorgebucaran** [comment]
@frenzzy I know what you mean. We'll see.

**Comment by jorgebucaran** [comment]
@frenzzy On a second thought, you're calling app twice in your example.

**Comment by frenzzy** [comment]
@jorgebucaran yes, but each time with a different container which is fine as I understand.

**Comment by frenzzy** [comment]
You always can preserve previous state if you want...
```js
const main = app(state, actions, view, container)

if (module.hot) {
  module.hot.dispose(function (hotData) {
    hotData.prevState = main.getState()
  });

  module.hot.accept(function (hotData) {
    const nextState = Object.assign({}, state, hotData.prevState) // or deep merge
    const nextContainer = document.body.appendChild(document.createElement('div'))
    app(nextState, actions, view, nextContainer)
  });
}
```

**Comment by frenzzy** [comment]
With [unmount feature](https://github.com/hyperapp/hyperapp/issues/637#issuecomment-378230188) you even may use the same container and avoid memory leaks:
```js
const main = withUnmount(app)(state, actions, view, container)

if (module.hot) {
  module.hot.dispose(function (hotData) {
    hotData.prevState = main.getState()
    main.unmount()
  });

  module.hot.accept(function (hotData) {
    const nextState = Object.assign({}, state, hotData.prevState) // or deep merge
    app(nextState, actions, view, container)
  });
}
```

**Pull request closed without merging**
