### PR TITLE
Update typescript definitions for 0.15.1: add Modules and init()

### PR DESCRIPTION
**Pull request by Mytrill**
Added definition for init() and Modules + example.
Fixes part of #409.

### CODE REVIEW

**Comment by pspeter3** [comment]
Did we change the code formatting?

**Comment by Mytrill** [comment]
Done.

**Comment by Mytrill** [comment]
Question: who here would be in favor of adding default types to all the generics, e.g.
```typescript
Actions<State extends ... = Hyperapp.State> { ... }
```
Can you upvote/downvote on this coment?

**Comment by Mytrill** [comment]
Hey all, as per @JorgeBucaran 's request, I am posting here an example use (also fount in `test/ts/index.tsx`).

I am not very happy with the current state of this PR, as defining modules is very verbose (for each module, users have to define the global state/actions, and optionally, the module's own state/actions).

Please let me know what you think/if you have any suggestions.

```typescript
// Sub-module (used by Module 1)

interface SubModuleState extends Hyperapp.State {
  count: number
}

interface SubModuleActions extends Hyperapp.Actions<Module1State> {
  sub(value: number): Partial<Module1State>
  add(value: number): Partial<Module1State>
}

// no need to specify OwnState and OwnActions here since it defaults to full state/actions
const submodule: Hyperapp.Module<SubModuleState, SubModuleActions> = {
  state: {
    count: 0
  },
  actions: {
    sub: (state, actions, value: number) => ({ count: state.count - value }),
    add: (state, actions, value: number) => ({ count: state.count + value })
  },
  init(state, actions) {
    console.log('Current count (typed!): ' + state.count)
  }
}

// Module 1 (utilize modules feature)

// only its own state
interface Module1OwnState extends Hyperapp.State {
  count: number
}
// state including sub-modules
interface Module1State extends Module1OwnState {
  submodule: SubModuleState
}
// only its own actions
interface Module1OwnActions extends Hyperapp.Actions<Module1OwnState> {
  sub(value: number): Partial<Module1State>
  add(value: number): Partial<Module1State>
}
// actions including sub-modules
interface Module1Actions extends Module1OwnActions {
  submodule: SubModuleActions
}

const module1: Hyperapp.Module<
  Module1State,
  Module1Actions,
  Module1OwnState,
  Module1OwnActions
> = {
  state: {
    count: 0
  },
  actions: {
    sub: (state, actions, value: number) => ({ count: state.count - value }),
    add: (state, actions, value: number) => ({ count: state.count + value })
  },
  init(state, actions) {
    console.log('Current count (typed!): ' + state.count)
  },
  modules: {
    // unfortunately, the type system doesn't enforce anything here...
    // we may be able to make it better by using Omit/Diff from https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-311923766
    submodule
  }
}
```

**Comment by pspeter3** [comment]
I don't mind removing verbosity as long as the types are correct. I'd be interested in the Diff/Omit types at the bottom. I think part of the difficulty is the implicitness of modules and the fact that actions have two types.

**Comment by JorgeBucaran** [comment]
I don't use TS, so I don't feel the pain, but I know that if I was a beginner and wanted to try TypeScript and saw this I would be discouraged. I vote for giving users a better experience rather than 100% accuracy.

@pspeter3 Is this the best TypeScript can do?

**Comment by pspeter3** [comment]
I'm not sure. I haven't spent a lot of time thinking about it too deeply.

**Comment by JorgeBucaran** [comment]
Hey guys! @Mytrill @Swizz What do you think we should do about this one?

**Comment by Mytrill** [comment]
No one voted for/against adding default types, so I will not change that, and regarding the modules, this is the simplest working typings I could get that actually provide the user with compiler help.

So I vote for merging this.

**Comment by okwolf** [comment]
> Mytrill wants to merge 2 commits into `hyperapp:master` from `unknown repository`

😮

**Comment by JorgeBucaran** [comment]
@Swizz Ping.

**Comment by Mytrill** [comment]
@okwolf yes I had to recreate the fork to create a new PR: I am git impaired :D

**Comment by Swizz** [comment]
Sorry for the late review. I always find the typing usage heavy about Hyperapp. There is a lot of thing to type before being ready to use the `app` function. But I think @okwolf did an incredible job to make it comprehensible.

I do not really understand the use of `Record` here.
But all this typing stuff LGTM. Finally me review wasn't needed ^^

**Comment by JorgeBucaran** [comment]
@Swizz @Mytrill did 😉 

...but @okwolf is an all-around, nice guy too.

**Comment by Swizz** [comment]
Oups, I apologize. :confused: 
> @Mytrill  @okwolf did an incredible job to make it comprehensible

**Comment by Mytrill** [comment]
@JorgeBucaran I think we aren't waiting on anymore feedback for this? Could you merge it? :)

@Swizz the Record Allows to write A in key of Actions and State[A], which allows for some level of type checking on the shape of the actions object's shape

**Comment by JorgeBucaran** [comment]
Merged, merged, merged. 🎉

**Comment by SkaterDad** [comment]
@JorgeBucaran Does this need a patch release in order for us to use the new definitions in our editors?  I know VSCode tries to get defs automatically, but have no clue where it tries to find them.

**Comment by pspeter3** [comment]
It finds them in the current package or Definitely Typed. You'll need to do
a point release

**Comment by JorgeBucaran** [comment]
@SkaterDad Yes, I'll publish a new patch today! 🙏

**Pull request merged**
