### PR TITLE
Set inline handler for non-function values

### PR DESCRIPTION
**Pull request by itrelease**

### CODE REVIEW

**Comment by itrelease** [comment]
For things like ```<div onclick="alert(1)">whoa</div>```

**Comment by jbucaran** [comment]
> @itrelease For things like `<div onclick="alert(1)">whoa</div>`

Ah, I get it. 🤔 
Seems like a pointless thing to do that would just increase the bundle size, when you can simply do instead:

```js
<div onclick=${_ => alert(1)}>Whoa</div>
```

**Comment by itrelease** [comment]
@jbucaran fair point I guess

**Comment by jbucaran** [comment]
@itrelease Awesome! Thanks.

**Pull request closed without merging**
