### PR TITLE
Enter the dark side: rewrite some tests using JSX. 

### PR DESCRIPTION
**Pull request by jorgebucaran**
Use JSX in tests (like I used to back in the day). I tried to fall in love with `h`, but old habits kept getting in the way. I confess I personally find JSX a lot easier to understand than nested `h` calls. Perhaps my brain is wired to look at HTML-like trees and instantly visualize what's going on. Sorry, JSX detractors, I just can't get used to `h`. 

> P.S: `@hyperapp/html` is also a valid alternative, but it's easier to use JSX with Jest and since we're using Jest...

### CODE REVIEW

**Comment by lukejacksonn** [comment]
You know my stance on this topic.. but in case I have not said enough, it is one thing supporting a proprietary syntax and for app developers to construct vnodes (because old habits die hard), it is another to integrate this dependency at such a low level as testing.

Now we have to transpile tests? What is JSX changes, all your tests break? Don't take this as overly negative.. but this proposal is absurd.

**Comment by jorgebucaran** [comment]
> @lukejacksonn Now we have to transpile tests? What if JSX changes, all your tests break?

I don't think JSX is going to change in a way that could break any of these tests.

**Comment by frenzzy** [comment]
Personally, I do not understand why this was not done from the beginning, JSX in the tests are really much more readable!

Here for example tests for [`@hyperapp/render`](https://github.com/hyperapp/render) using JSX: https://github.com/hyperapp/render/blob/master/test/index.test.js

**Comment by jorgebucaran** [comment]
We used to, but then I changed it back when I thought I could also get rid of babel. The problem is we need babel with jest so that tests can be written using ES modules.

**Comment by jorgebucaran** [comment]
The docs use JSX and we've been "promoting" JSX (while offering alternatives too) for a while. For better or for worse, the best way to introduce HA to a frontend developer coming from React is as an opinionated, tiny React & Redux. It's too late to pretend JSX is not a VIP first-class citizen in HA. 😄

**Comment by Swizz** [comment]
I would love to keep tests bare metal. 
Using JSX in tests seem a little bit too overpowered.

**Comment by jorgebucaran** [comment]
Sorry, folks, but I am nearly done porting the tests and made up my mind about this one. 😈  

Look, I am always afraid to touch the tests because they're too difficult to maintain and JSX made almost all the pain go away.

**Pull request merged**
