### PR TITLE
Create the default root element and initial render after the document is ready

### PR DESCRIPTION
**Pull request by tzellman**
It seems safest to wait until the document is ready before we attempt to:

* create the default root element
* initially call `render`

### CODE REVIEW

**Comment by tzellman** [comment]
I might need to make a slight mod to rebase with the changes made in 4126833.

**Comment by jbucaran** [comment]
> It seems safest to wait until the document is ready before we attempt to:

Playing devil's advocate here: why is it safest? and also, how come we were not getting errors?

**Comment by jbucaran** [comment]
> @tzellman It seems safest to wait until the document is ready before we attempt to:

Playing devil's advocate here: why is it safest? and also, how come we were not getting any errors until now? That could be indicating a deeper problem.

**Comment by dodekeract** [comment]
@jbucaran If that's helpful I definitely already had that issue in `0.0.7`. Took a while to understand while the `subs` didn't work, but made sense that the event never fired when executing `app` on `load`.

**Comment by jbucaran** [comment]
@dodekeract Minor correction, it's `subscriptions` now.

**Comment by tzellman** [comment]
The reason I made the change was strictly due to potential timing issues. If your JS runs in the `<head>` tag, then it is possible to attempt to create the default root element before the DOM is ready. Same goes for the `render` method, in case you passed in a truthy value for root.

**Comment by dodekeract** [comment]
@jbucaran You mean #69. 🙂

**Comment by jbucaran** [comment]
Yup. 😅

**Comment by tzellman** [comment]
Just posted a comment with example in #69.

**Comment by jbucaran** [comment]
What do other frameworks do in this instance? Does anybody know?

**Comment by dodekeract** [comment]
@jbucaran React definitely doesn't work, because you have to manually give `ReactDOM.render()` a DOMElement. I guess it's a bit more low-level than hyperapp in that regard.

**Comment by jbucaran** [comment]
@dodekeract Try `app({ root: document.body })`.

**Comment by jbucaran** [comment]
Root elements, subscriptions and initial render (incl. router support) landed in master. 
* https://github.com/hyperapp/hyperapp/blob/7e248b2fbeeed757030a8ec96a520af624810a44/src/app.js#L43. 

Thank you @tzellman for bringing this up!

**Pull request closed without merging**
