### PR TITLE
Remove the router

### PR DESCRIPTION
**Pull request by jbucaran**

### CODE REVIEW

**Comment by dodekeract** [comment]
So how are we supposed to do anything with hyperapp now?

**Comment by jbucaran** [comment]
The router will live [here](https://github.com/hyperapp/router).

**Comment by jrop** [comment]
I was just playing around with this because I needed a hash-router (due to constraints, I cannot use pushState), and came up with this:

Code:
https://glitch.com/edit/#!/brainy-ferryboat

Preview:
https://brainy-ferryboat.glitch.me/

**Comment by lukejacksonn** [comment]
Nice! I feel like someone has already had a go at a hash based router, or adapted the hyperapp router to work with hashes 🤔 can't remember who though

**Comment by zaceno** [comment]
There's this: https://github.com/zaceno/hyperapp-hash-router

... which is basically just a search-and-replace of hyperapps built in router. (doesn't even have a package.json so you can import it though)

**Pull request merged**
