### PR TITLE
oldProps→oldAttributes in README.md

### PR DESCRIPTION
**Pull request by frenzzy**
continues 25b85ef848c40b7030ecb7241ee55b49e4ef84fd

### CODE REVIEW

**Comment by frenzzy** [comment]
maybe `prevAttributes` is better name?

**Comment by JorgeBucaran** [comment]
@frenzzy What if we just call them old <samp>attributes</samp>?

**Comment by frenzzy** [comment]
Second argument of `onupdate` is actually previous VNode attributes. If we call it just `attributes` it may confuse users. Also `old` prefix in my mind is some version in the past, not exactly previous. And `prevAttributes` explains what it really is.

**Comment by JorgeBucaran** [comment]
Ah, well you are right. About `old` vs `previous`. We are already using `old` internally and in the docs, so I prefer we use `old` here too.

**Comment by JorgeBucaran** [comment]
Thanks, @frenzzy!

**Pull request merged**
