### PR TITLE
changed 'data' to 'attributes' at getting-started.md

### PR DESCRIPTION
**Pull request by dividedbynil**
Avoid ambiguity.

### CODE REVIEW

**Comment by jbucaran** [comment]
Hi @dividedbynil! 

I am not sure what to do here. [We use `data` internally](https://github.com/hyperapp/hyperapp/blob/436ed891f8d3d2df341b82b47f63fe2896cffb31/src/h.js#L26), so if I accept this change, shouldn't we actually change the code as well?

**Comment by dividedbynil** [comment]
Hi @jbucaran, thanks for quick response, you mean the data is not just defining the HTML attributes?

**Comment by jamen** [comment]
We use `node.data` several places inside `src/app.js` as well.  Are we only changing the signature here?  I would be more keen on approving this if it was changed across the entire library.

**Comment by jbucaran** [comment]
To be honest I am not what the confusion is.

**Comment by dividedbynil** [comment]
@jamen Hi, I will work on changing the entire library, by using 'attr', is it better instead of 'data'? @jbucaran

**Comment by jbucaran** [comment]
@dividedbynil Thanks for the effort, but no need to. 👋  `.data` is part of the internal API and end users are unlikely to have to deal with this.

**Comment by dividedbynil** [comment]
@jbucaran Okay, no problem.

**Pull request closed without merging**
