### PR TITLE
reduce router regex length

### PR DESCRIPTION
**Pull request by lazarljubenovic**
The tests are passing but I'm not 100% sure this is equivalent, although by definition it should be. Tests aren't really targeting this area much.

### CODE REVIEW

**Comment by jbucaran** [comment]
@lazarljubenovic Can we add a test for this? 🙏

**Comment by lazarljubenovic** [comment]
I think that whoever's written the original regex should add tests. Whatever I write will be biased towards `\w` (and will work with both versions) because that's how I "see" the original one.

**Comment by lazarljubenovic** [comment]
Got merged here https://github.com/hyperapp/hyperapp/pull/207

**Comment by jbucaran** [comment]
Thanks @lazarljubenovic! 🙏

**Pull request closed without merging**
