### PR TITLE
Update types for 1.0.0

### PR DESCRIPTION
**Pull request by Mytrill**
Update the typescript type definitions for 1.0.0 PR.

### CODE REVIEW

**Comment by JorgeBucaran** [comment]
🎉 🎉

**Comment by JorgeBucaran** [comment]
@Mytrill 

- `VNodeChild`→`VChildNode` (What do you think?)
- `State` and `Actions` are required, `View` and container are optional.
- Rename `ActionsImpl` and `ActionImpl`
  - Options
     - ActionsModel
     - ActionsTemplate
     - ActionsType
     - MyActions
     - WiredActions

**Comment by SkaterDad** [comment]
While you're at it, could you replace the empty object types (`{ }`) with `object`?  It's more specific and disallows the other primitive types which JS also considers objects.

**Comment by JorgeBucaran** [comment]
@Mytrill We just need a good name for the actions implementation type. Here are some ideas:

- ActionsModel
- ActionsType

**Comment by JorgeBucaran** [comment]
Thanks @Mytrill! This looks amazing! 🎉

**Comment by Nike1016** [comment]
7c705610-e66f-4aa7-ab4b-86d65aa1ebd7

**Pull request merged**
