### PR TITLE
Inline styles

### PR DESCRIPTION
**Pull request by frenzzy**
It allows us to use bunch of valid html/svg code inside vdom tree without the need to convert a lot of inline styles into objects.

Fixes https://github.com/hyperapp/hyperapp/issues/672#issuecomment-377783572

Demo: https://codepen.io/frenzzy/pen/OvEyeL/left/?editors=0010

### CODE REVIEW

**Comment by jorgebucaran** [comment]
I'd like to compare this with using cssText when style is a string.

**Comment by jorgebucaran** [comment]
@frenzzy Close here?

**Comment by frenzzy** [comment]
@jorgebucaran why do you think `cssText` version is better? This version looks shorter.
Possible issue could be a browser support here, but I haven't checked it yet.

**Comment by jorgebucaran** [comment]
Thanks, @frenzzy. I am going to abandon this feature for the same reason given [here](https://github.com/facebook/react/issues/5397#issuecomment-153954732) as I hold the same opinion.

**Pull request closed without merging**
