### PR TITLE
Render virtual DOM node to HTML string

### PR DESCRIPTION
**Pull request by benjaminj6**
#14 

Maybe a starting point rather than full implementation for server side rendering as it currently only spits out static html. 

The other thing I could see is to put it in a separate package so the client-side bundle size doesn't suffer. I'd love to hear what the preferred path forward is for that.

Let me know your thoughts!

### CODE REVIEW

**Comment by AutoSponge** [comment]
I didn't see `key` being omitted from the string renderer. I also think dataset may need to be handled explicitly. There may be other edge cases I'm not thinking of.

**Comment by jbucaran** [comment]
@AutoSponge Thanks!

@benjaminj6 Good job! With regards to:

> The other thing I could see is to put it in a separate package so the client-side bundle size doesn't suffer. I'd love to hear what the preferred path forward is for that.

I think definitely put it in a separate package is the way to go.

/cc @dodekeract @lukejacksonn @selfup

**Comment by dodekeract** [comment]
@jbucaran React handles this by letting you import `react-dom/server`. I see no reason why we can't do the same here.

**Comment by jbucaran** [comment]
@dodekeract Ah, that makes sense too. 

@benjaminj6 I think this means we don't need the changes in index.js.

**Comment by benjaminj6** [comment]
@jbucaran @dodekeract That makes total sense, will take those changes out. While we're at it, I was thinking about file names this morning and I wonder if `hyperapp/server` would be preferable. Let me know and I'll go ahead and change that too.

**Comment by jbucaran** [comment]
@benjaminj6 @dodekeract What do you think? I always thought `toString` was the best.

**Comment by benjaminj6** [comment]
I'd be happy with `toString`

**Comment by dodekeract** [comment]
@jbucaran You're forgetting that server rendering doesn't mean "offer a toString function". It means that the whole app can run on the server-side. So we need to **at least** accept state and fire `load`.

**Comment by jbucaran** [comment]
@dodekeract Actually, I have no idea. 😅 

If you want to take care of this issue and sort it out, please do! 👋

**Comment by dodekeract** [comment]
@jbucaran Well, we do need a `toString` function for sure. But we also need to take care of the rest.

Essentially, when server-rendering the only thing that should change is the `app()` function. It should render to a string instead of the DOM, but it should still work the same. E.g. contain actions, etc..

The only problem here is that we'll need to make sure to never leak memory. That's fatal on a server.

To begin working on this we basically only need `app({state, view})`. Then, we need to find a solution for the router. My suggestion regarding that still is to include the URL-state in `state.router.url`. I think now you're slowly noticing the point I talked to you about regarding "all state should be in `state`, URL gets rendered from `state`, not the other way around".

In the long term, we need a complete drop-in replacement for `app()`, which accepts `state`, `view`, `events` (load is probably important?), `actions`, `plugins`.

**Comment by jbucaran** [comment]
@dodekeract I thought a toString was good enough. If we're going to go this route, might as well create a separate repo.

**Comment by benjaminj6** [comment]
@dodekeract @jbucaran 

I think a `toString` function is still valuable/needed — especially with the rise of static site generators (the whole [JAMstack](https://jamstack.org/) thing comes to mind).

But I also agree that eventually we should implement true ssr, perhaps in a separate repo. Especially if we want people to start using `hyperapp` more 😎

**Comment by jbucaran** [comment]
Thanks @benjaminj6! You are probably right. In that case, I think we should go ahead and create a new repo and take care of it proper. Would you like to take the lead?

I can send you an org invite so you can create it yourself.

**Comment by benjaminj6** [comment]
@jbucaran I'd love to! Shoot me that invite and I'll get on it .

**Comment by benjaminj6** [comment]
Cool! Hopefully gonna be able to get it done this weekend now that I have a little bit of free time 🎉

**Comment by benjaminj6** [comment]
Ok so we've got a [repo](https://github.com/hyperapp/hyperapp-server) for ssr set up 🎉

Let's move this discussion over there. I just started by moving the `toString` into it for static rendering and opening an [issue](https://github.com/hyperapp/hyperapp-server/issues/2) regarding a server-side implementation of `app`. I still need to do a little more research/need a little input on _how_ to go about that though 😎

**Pull request closed without merging**
