### PR TITLE
JSX example code fixed

### PR DESCRIPTION
**Pull request by ChristianHarms**
I followed your documentation and built a working webpack / jsx setup. But I got an error. After checking my code and your examples it was only the calling action code from the example.

### CODE REVIEW

**Comment by selfup** [comment]
Works fine here: https://github.com/selfup/hyperapp-one/blob/master/src/components/Counter.js#L16

**Comment by ChristianHarms** [comment]
I am so sorry. I changed the wrong documentation. In the helloworld.md example is a small section of the JXS part and this was not working with the actions above.

**Comment by selfup** [comment]
No worries! Thanks for fixing 🎉 

Now time to wait for @JorgeBucaran 🙏

**Comment by JorgeBucaran** [comment]
Thanks! :)

**Pull request merged**
